package xxqp.oracle.apps.ar.pdft.conscliente.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClientesInfoVOImpl extends OAViewObjectImpl {
  /**This is the default constructor (do not remove)
   */
  public ClientesInfoVOImpl()
  {
  }

  void filterConsultaCliente(String pStrNombreDelCliente
                           , String pStrRFC
                           , String pStrRazonSocial
                           , String pStrEstado)
  {
    if((null==pStrNombreDelCliente||"".equals(pStrNombreDelCliente))
    &&(null==pStrRFC||"".equals(pStrRFC))
    &&(null==pStrRazonSocial||"".equals(pStrRazonSocial))
    &&(null==pStrEstado||"".equals(pStrEstado))
    ){
     return;
    }
    /* 2. Create a view criteria row set for this view object  */
    ViewCriteria vc = this.createViewCriteria(); 
    /* 3. Use the view criteria to create one or more view criteria rows  */
    ViewCriteriaRow vcr1 = vc.createViewCriteriaRow(); 
    /* 4. Set attribute values to filter on in appropriate view criteria rows */ 
    if(null!=pStrNombreDelCliente&&!"".equals(pStrNombreDelCliente)){
    vcr1.setAttribute("KnownAs",pStrNombreDelCliente); 
    }
    if(null!=pStrRFC&&!"".equals(pStrRFC)){
    vcr1.setAttribute("JgzzFiscalCode",pStrRFC); 
    }
    if(null!=pStrRazonSocial&&!"".equals(pStrRazonSocial)){
    vcr1.setAttribute("RazonSocial",pStrRazonSocial); 
    }
    if(null!=pStrEstado&&!"".equals(pStrEstado)){
    vcr1.setAttribute("State",pStrEstado); 
    }
    /* 5. Add the view criteria rows to the view critera row set */
    vc.add(vcr1); 
    /* 6. Apply the view criteria to the view object */ 
    this.applyViewCriteria(vc); 
    /* 7. Execute the query */
    this.executeQuery();
    
    
    
  }

  void cleanConsultaCliente()
  {
    /* 2. Create a view criteria row set for this view object  */
    ViewCriteria vc = this.createViewCriteria(); 
    /* 3. Use the view criteria to create one or more view criteria rows  */
    ViewCriteriaRow vcr1 = vc.createViewCriteriaRow(); 
    /* 4. Set attribute values to filter on in appropriate view criteria rows */ 
    vcr1.setAttribute("PartyId",new oracle.jbo.domain.Number(-1)); 
    /* 5. Add the view criteria rows to the view critera row set */
    vc.add(vcr1); 
    /* 6. Apply the view criteria to the view object */ 
    this.applyViewCriteria(vc); 
    /* 7. Execute the query */
    this.executeQuery();
  }
  
}
