package xxqp.oracle.apps.ar.pdft.conscliente.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClientesInfoVORowImpl extends OAViewRowImpl {
    public static final int PARTYID = 0;
    public static final int PARTYNAME = 1;
    public static final int PERSONFIRSTNAME = 2;
    public static final int PERSONLASTNAME = 3;
    public static final int PARTYTYPE = 4;
    public static final int TYPELOOKUP = 5;
    public static final int PARTYNUMBER = 6;
    public static final int TAXREFERENCE = 7;
    public static final int TAXPAYERID = 8;
    public static final int DUNSNUMBER = 9;
    public static final int KNOWNAS = 10;
    public static final int KNOWNAS2 = 11;
    public static final int KNOWNAS3 = 12;
    public static final int KNOWNAS4 = 13;
    public static final int KNOWNAS5 = 14;
    public static final int ORGANIZATIONNAMEPHONETIC = 15;
    public static final int PERSONFIRSTNAMEPHONETIC = 16;
    public static final int PERSONLASTNAMEPHONETIC = 17;
    public static final int LOCATIONID = 18;
    public static final int COUNTRY = 19;
    public static final int PRIMARYPHONECONTACTPTID = 20;
    public static final int PRIMARYPHONECOUNTRYCODE = 21;
    public static final int PRIMARYPHONEAREACODE = 22;
    public static final int PRIMARYPHONENUMBER = 23;
    public static final int PRIMARYPHONELINETYPE = 24;
    public static final int PRIMARYPHONEEXTENSION = 25;
    public static final int EMAIL = 26;
    public static final int PRIMARYURL = 27;
    public static final int CERTIFICATIONLEVELMEANING = 28;
    public static final int REGISTRYMEANING = 29;
    public static final int PARTYSTATUS = 30;
    public static final int CITY = 31;
    public static final int JGZZFISCALCODE = 32;
    public static final int RAZONSOCIAL = 33;
    public static final int STATE = 34;
    public static final int ATTRIBUTECATEGORY = 35;
    public static final int ATTRIBUTE1 = 36;
    public static final int ATTRIBUTE2 = 37;
    public static final int HCSUAORGID = 38;
    public static final int HCASAORGID = 39;

    /**This is the default constructor (do not remove)
     */
  public ClientesInfoVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute PartyId
   */
  public Number getPartyId()
  {
    return (Number) getAttributeInternal(PARTYID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PartyId
   */
  public void setPartyId(Number value)
  {
    setAttributeInternal(PARTYID, value);
  }

  /**Gets the attribute value for the calculated attribute PartyName
   */
  public String getPartyName()
  {
    return (String) getAttributeInternal(PARTYNAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PartyName
   */
  public void setPartyName(String value)
  {
    setAttributeInternal(PARTYNAME, value);
  }

  /**Gets the attribute value for the calculated attribute PersonFirstName
   */
  public String getPersonFirstName()
  {
    return (String) getAttributeInternal(PERSONFIRSTNAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonFirstName
   */
  public void setPersonFirstName(String value)
  {
    setAttributeInternal(PERSONFIRSTNAME, value);
  }

  /**Gets the attribute value for the calculated attribute PersonLastName
   */
  public String getPersonLastName()
  {
    return (String) getAttributeInternal(PERSONLASTNAME);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonLastName
   */
  public void setPersonLastName(String value)
  {
    setAttributeInternal(PERSONLASTNAME, value);
  }

  /**Gets the attribute value for the calculated attribute PartyType
   */
  public String getPartyType()
  {
    return (String) getAttributeInternal(PARTYTYPE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PartyType
   */
  public void setPartyType(String value)
  {
    setAttributeInternal(PARTYTYPE, value);
  }

  /**Gets the attribute value for the calculated attribute TypeLookup
   */
  public String getTypeLookup()
  {
    return (String) getAttributeInternal(TYPELOOKUP);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TypeLookup
   */
  public void setTypeLookup(String value)
  {
    setAttributeInternal(TYPELOOKUP, value);
  }

  /**Gets the attribute value for the calculated attribute PartyNumber
   */
  public String getPartyNumber()
  {
    return (String) getAttributeInternal(PARTYNUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PartyNumber
   */
  public void setPartyNumber(String value)
  {
    setAttributeInternal(PARTYNUMBER, value);
  }

  /**Gets the attribute value for the calculated attribute TaxReference
   */
  public String getTaxReference()
  {
    return (String) getAttributeInternal(TAXREFERENCE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TaxReference
   */
  public void setTaxReference(String value)
  {
    setAttributeInternal(TAXREFERENCE, value);
  }

  /**Gets the attribute value for the calculated attribute TaxpayerId
   */
  public String getTaxpayerId()
  {
    return (String) getAttributeInternal(TAXPAYERID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TaxpayerId
   */
  public void setTaxpayerId(String value)
  {
    setAttributeInternal(TAXPAYERID, value);
  }

  /**Gets the attribute value for the calculated attribute DunsNumber
   */
  public String getDunsNumber()
  {
    return (String) getAttributeInternal(DUNSNUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute DunsNumber
   */
  public void setDunsNumber(String value)
  {
    setAttributeInternal(DUNSNUMBER, value);
  }

  /**Gets the attribute value for the calculated attribute KnownAs
   */
  public String getKnownAs()
  {
    return (String) getAttributeInternal(KNOWNAS);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute KnownAs
   */
  public void setKnownAs(String value)
  {
    setAttributeInternal(KNOWNAS, value);
  }

  /**Gets the attribute value for the calculated attribute KnownAs2
   */
  public String getKnownAs2()
  {
    return (String) getAttributeInternal(KNOWNAS2);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute KnownAs2
   */
  public void setKnownAs2(String value)
  {
    setAttributeInternal(KNOWNAS2, value);
  }

  /**Gets the attribute value for the calculated attribute KnownAs3
   */
  public String getKnownAs3()
  {
    return (String) getAttributeInternal(KNOWNAS3);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute KnownAs3
   */
  public void setKnownAs3(String value)
  {
    setAttributeInternal(KNOWNAS3, value);
  }

  /**Gets the attribute value for the calculated attribute KnownAs4
   */
  public String getKnownAs4()
  {
    return (String) getAttributeInternal(KNOWNAS4);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute KnownAs4
   */
  public void setKnownAs4(String value)
  {
    setAttributeInternal(KNOWNAS4, value);
  }

  /**Gets the attribute value for the calculated attribute KnownAs5
   */
  public String getKnownAs5()
  {
    return (String) getAttributeInternal(KNOWNAS5);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute KnownAs5
   */
  public void setKnownAs5(String value)
  {
    setAttributeInternal(KNOWNAS5, value);
  }

  /**Gets the attribute value for the calculated attribute OrganizationNamePhonetic
   */
  public String getOrganizationNamePhonetic()
  {
    return (String) getAttributeInternal(ORGANIZATIONNAMEPHONETIC);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute OrganizationNamePhonetic
   */
  public void setOrganizationNamePhonetic(String value)
  {
    setAttributeInternal(ORGANIZATIONNAMEPHONETIC, value);
  }

  /**Gets the attribute value for the calculated attribute PersonFirstNamePhonetic
   */
  public String getPersonFirstNamePhonetic()
  {
    return (String) getAttributeInternal(PERSONFIRSTNAMEPHONETIC);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonFirstNamePhonetic
   */
  public void setPersonFirstNamePhonetic(String value)
  {
    setAttributeInternal(PERSONFIRSTNAMEPHONETIC, value);
  }

  /**Gets the attribute value for the calculated attribute PersonLastNamePhonetic
   */
  public String getPersonLastNamePhonetic()
  {
    return (String) getAttributeInternal(PERSONLASTNAMEPHONETIC);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PersonLastNamePhonetic
   */
  public void setPersonLastNamePhonetic(String value)
  {
    setAttributeInternal(PERSONLASTNAMEPHONETIC, value);
  }

  /**Gets the attribute value for the calculated attribute LocationId
   */
  public Number getLocationId()
  {
    return (Number) getAttributeInternal(LOCATIONID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute LocationId
   */
  public void setLocationId(Number value)
  {
    setAttributeInternal(LOCATIONID, value);
  }

  /**Gets the attribute value for the calculated attribute Country
   */
  public String getCountry()
  {
    return (String) getAttributeInternal(COUNTRY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Country
   */
  public void setCountry(String value)
  {
    setAttributeInternal(COUNTRY, value);
  }

  /**Gets the attribute value for the calculated attribute PrimaryPhoneContactPtId
   */
  public Number getPrimaryPhoneContactPtId()
  {
    return (Number) getAttributeInternal(PRIMARYPHONECONTACTPTID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PrimaryPhoneContactPtId
   */
  public void setPrimaryPhoneContactPtId(Number value)
  {
    setAttributeInternal(PRIMARYPHONECONTACTPTID, value);
  }

  /**Gets the attribute value for the calculated attribute PrimaryPhoneCountryCode
   */
  public String getPrimaryPhoneCountryCode()
  {
    return (String) getAttributeInternal(PRIMARYPHONECOUNTRYCODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PrimaryPhoneCountryCode
   */
  public void setPrimaryPhoneCountryCode(String value)
  {
    setAttributeInternal(PRIMARYPHONECOUNTRYCODE, value);
  }

  /**Gets the attribute value for the calculated attribute PrimaryPhoneAreaCode
   */
  public String getPrimaryPhoneAreaCode()
  {
    return (String) getAttributeInternal(PRIMARYPHONEAREACODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PrimaryPhoneAreaCode
   */
  public void setPrimaryPhoneAreaCode(String value)
  {
    setAttributeInternal(PRIMARYPHONEAREACODE, value);
  }

  /**Gets the attribute value for the calculated attribute PrimaryPhoneNumber
   */
  public String getPrimaryPhoneNumber()
  {
    return (String) getAttributeInternal(PRIMARYPHONENUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PrimaryPhoneNumber
   */
  public void setPrimaryPhoneNumber(String value)
  {
    setAttributeInternal(PRIMARYPHONENUMBER, value);
  }

  /**Gets the attribute value for the calculated attribute PrimaryPhoneLineType
   */
  public String getPrimaryPhoneLineType()
  {
    return (String) getAttributeInternal(PRIMARYPHONELINETYPE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PrimaryPhoneLineType
   */
  public void setPrimaryPhoneLineType(String value)
  {
    setAttributeInternal(PRIMARYPHONELINETYPE, value);
  }

  /**Gets the attribute value for the calculated attribute PrimaryPhoneExtension
   */
  public String getPrimaryPhoneExtension()
  {
    return (String) getAttributeInternal(PRIMARYPHONEEXTENSION);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PrimaryPhoneExtension
   */
  public void setPrimaryPhoneExtension(String value)
  {
    setAttributeInternal(PRIMARYPHONEEXTENSION, value);
  }

  /**Gets the attribute value for the calculated attribute Email
   */
  public String getEmail()
  {
    return (String) getAttributeInternal(EMAIL);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Email
   */
  public void setEmail(String value)
  {
    setAttributeInternal(EMAIL, value);
  }

  /**Gets the attribute value for the calculated attribute PrimaryUrl
   */
  public String getPrimaryUrl()
  {
    return (String) getAttributeInternal(PRIMARYURL);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PrimaryUrl
   */
  public void setPrimaryUrl(String value)
  {
    setAttributeInternal(PRIMARYURL, value);
  }

  /**Gets the attribute value for the calculated attribute CertificationLevelMeaning
   */
  public String getCertificationLevelMeaning()
  {
    return (String) getAttributeInternal(CERTIFICATIONLEVELMEANING);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute CertificationLevelMeaning
   */
  public void setCertificationLevelMeaning(String value)
  {
    setAttributeInternal(CERTIFICATIONLEVELMEANING, value);
  }

  /**Gets the attribute value for the calculated attribute RegistryMeaning
   */
  public String getRegistryMeaning()
  {
    return (String) getAttributeInternal(REGISTRYMEANING);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute RegistryMeaning
   */
  public void setRegistryMeaning(String value)
  {
    setAttributeInternal(REGISTRYMEANING, value);
  }

  /**Gets the attribute value for the calculated attribute PartyStatus
   */
  public String getPartyStatus()
  {
    return (String) getAttributeInternal(PARTYSTATUS);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PartyStatus
   */
  public void setPartyStatus(String value)
  {
    setAttributeInternal(PARTYSTATUS, value);
  }

  /**Gets the attribute value for the calculated attribute City
   */
  public String getCity()
  {
    return (String) getAttributeInternal(CITY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute City
   */
  public void setCity(String value)
  {
    setAttributeInternal(CITY, value);
  }

  /**Gets the attribute value for the calculated attribute JgzzFiscalCode
   */
  public String getJgzzFiscalCode()
  {
    return (String) getAttributeInternal(JGZZFISCALCODE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute JgzzFiscalCode
   */
  public void setJgzzFiscalCode(String value)
  {
    setAttributeInternal(JGZZFISCALCODE, value);
  }

  /**Gets the attribute value for the calculated attribute RazonSocial
   */
  public String getRazonSocial()
  {
    return (String) getAttributeInternal(RAZONSOCIAL);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute RazonSocial
   */
  public void setRazonSocial(String value)
  {
    setAttributeInternal(RAZONSOCIAL, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case PARTYID:
            return getPartyId();
        case PARTYNAME:
            return getPartyName();
        case PERSONFIRSTNAME:
            return getPersonFirstName();
        case PERSONLASTNAME:
            return getPersonLastName();
        case PARTYTYPE:
            return getPartyType();
        case TYPELOOKUP:
            return getTypeLookup();
        case PARTYNUMBER:
            return getPartyNumber();
        case TAXREFERENCE:
            return getTaxReference();
        case TAXPAYERID:
            return getTaxpayerId();
        case DUNSNUMBER:
            return getDunsNumber();
        case KNOWNAS:
            return getKnownAs();
        case KNOWNAS2:
            return getKnownAs2();
        case KNOWNAS3:
            return getKnownAs3();
        case KNOWNAS4:
            return getKnownAs4();
        case KNOWNAS5:
            return getKnownAs5();
        case ORGANIZATIONNAMEPHONETIC:
            return getOrganizationNamePhonetic();
        case PERSONFIRSTNAMEPHONETIC:
            return getPersonFirstNamePhonetic();
        case PERSONLASTNAMEPHONETIC:
            return getPersonLastNamePhonetic();
        case LOCATIONID:
            return getLocationId();
        case COUNTRY:
            return getCountry();
        case PRIMARYPHONECONTACTPTID:
            return getPrimaryPhoneContactPtId();
        case PRIMARYPHONECOUNTRYCODE:
            return getPrimaryPhoneCountryCode();
        case PRIMARYPHONEAREACODE:
            return getPrimaryPhoneAreaCode();
        case PRIMARYPHONENUMBER:
            return getPrimaryPhoneNumber();
        case PRIMARYPHONELINETYPE:
            return getPrimaryPhoneLineType();
        case PRIMARYPHONEEXTENSION:
            return getPrimaryPhoneExtension();
        case EMAIL:
            return getEmail();
        case PRIMARYURL:
            return getPrimaryUrl();
        case CERTIFICATIONLEVELMEANING:
            return getCertificationLevelMeaning();
        case REGISTRYMEANING:
            return getRegistryMeaning();
        case PARTYSTATUS:
            return getPartyStatus();
        case CITY:
            return getCity();
        case JGZZFISCALCODE:
            return getJgzzFiscalCode();
        case RAZONSOCIAL:
            return getRazonSocial();
        case STATE:
            return getState();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case HCSUAORGID:
            return getHcsuaOrgId();
        case HCASAORGID:
            return getHcasaOrgId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case HCSUAORGID:
            setHcsuaOrgId((Number)value);
            return;
        case HCASAORGID:
            setHcasaOrgId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

  /**Gets the attribute value for the calculated attribute State
   */
  public String getState()
  {
    return (String) getAttributeInternal(STATE);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute State
   */
  public void setState(String value)
  {
    setAttributeInternal(STATE, value);
  }

    /**Gets the attribute value for the calculated attribute AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for the calculated attribute HcsuaOrgId
     */
    public Number getHcsuaOrgId() {
        return (Number) getAttributeInternal(HCSUAORGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute HcsuaOrgId
     */
    public void setHcsuaOrgId(Number value) {
        setAttributeInternal(HCSUAORGID, value);
    }

    /**Gets the attribute value for the calculated attribute HcasaOrgId
     */
    public Number getHcasaOrgId() {
        return (Number) getAttributeInternal(HCASAORGID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute HcasaOrgId
     */
    public void setHcasaOrgId(Number value) {
        setAttributeInternal(HCASAORGID, value);
    }
}
