package xxqp.oracle.apps.ar.pdft.conscliente.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RfcVORowImpl extends OAViewRowImpl {
    public static final int PARTYID = 0;
    public static final int TAXPAYERID = 1;

    /**This is the default constructor (do not remove)
     */
  public RfcVORowImpl()
  {
  }

  /**Gets the attribute value for the calculated attribute PartyId
   */
  public Number getPartyId()
  {
    return (Number) getAttributeInternal(PARTYID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute PartyId
   */
  public void setPartyId(Number value)
  {
    setAttributeInternal(PARTYID, value);
  }

  /**Gets the attribute value for the calculated attribute TaxpayerId
   */
  public String getTaxpayerId()
  {
    return (String) getAttributeInternal(TAXPAYERID);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute TaxpayerId
   */
  public void setTaxpayerId(String value)
  {
    setAttributeInternal(TAXPAYERID, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case PARTYID:
            return getPartyId();
        case TAXPAYERID:
            return getTaxpayerId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
