package xxqp.oracle.apps.ar.pdft.altafitec.masiplat.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MypHeaderTmpVORowImpl extends OAViewRowImpl {
    public static final int LINEID = 0;
    public static final int UNIDADDENEGOCIOC = 1;
    public static final int EMPRESAQUEFACTURAC = 2;
    public static final int FRECUENCIAFACTURACIONC = 3;
    public static final int CONTRATOFILE = 4;
    public static final int CONTRATOFILENAME = 5;
    public static final int CONTRATO = 6;

    /**This is the default constructor (do not remove)
     */
    public MypHeaderTmpVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute UnidadDeNegocioC
     */
    public String getUnidadDeNegocioC() {
        return (String) getAttributeInternal(UNIDADDENEGOCIOC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UnidadDeNegocioC
     */
    public void setUnidadDeNegocioC(String value) {
        setAttributeInternal(UNIDADDENEGOCIOC, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINEID:
            return getLineId();
        case UNIDADDENEGOCIOC:
            return getUnidadDeNegocioC();
        case EMPRESAQUEFACTURAC:
            return getEmpresaQueFacturaC();
        case FRECUENCIAFACTURACIONC:
            return getFrecuenciaFacturacionC();
        case CONTRATOFILE:
            return getContratoFile();
        case CONTRATOFILENAME:
            return getContratoFileName();
        case CONTRATO:
            return getContrato();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINEID:
            setLineId((String)value);
            return;
        case UNIDADDENEGOCIOC:
            setUnidadDeNegocioC((String)value);
            return;
        case EMPRESAQUEFACTURAC:
            setEmpresaQueFacturaC((String)value);
            return;
        case FRECUENCIAFACTURACIONC:
            setFrecuenciaFacturacionC((String)value);
            return;
        case CONTRATOFILE:
            setContratoFile((BlobDomain)value);
            return;
        case CONTRATOFILENAME:
            setContratoFileName((String)value);
            return;
        case CONTRATO:
            setContrato((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute LineId
     */
    public String getLineId() {
        return (String) getAttributeInternal(LINEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LineId
     */
    public void setLineId(String value) {
        setAttributeInternal(LINEID, value);
    }

    /**Gets the attribute value for the calculated attribute EmpresaQueFacturaC
     */
    public String getEmpresaQueFacturaC() {
        return (String) getAttributeInternal(EMPRESAQUEFACTURAC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmpresaQueFacturaC
     */
    public void setEmpresaQueFacturaC(String value) {
        setAttributeInternal(EMPRESAQUEFACTURAC, value);
    }

    /**Gets the attribute value for the calculated attribute FrecuenciaFacturacionC
     */
    public String getFrecuenciaFacturacionC() {
        return (String) getAttributeInternal(FRECUENCIAFACTURACIONC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FrecuenciaFacturacionC
     */
    public void setFrecuenciaFacturacionC(String value) {
        setAttributeInternal(FRECUENCIAFACTURACIONC, value);
    }

    /**Gets the attribute value for the calculated attribute ContratoFile
     */
    public BlobDomain getContratoFile() {
        return (BlobDomain) getAttributeInternal(CONTRATOFILE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ContratoFile
     */
    public void setContratoFile(BlobDomain value) {
        if(null!=value){
          this.setContrato("Y");
        }else{
          this.setContrato("N");
        }
        setAttributeInternal(CONTRATOFILE, value);
    }

    /**Gets the attribute value for the calculated attribute ContratoFileName
     */
    public String getContratoFileName() {
        return (String) getAttributeInternal(CONTRATOFILENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ContratoFileName
     */
    public void setContratoFileName(String value) {
        setAttributeInternal(CONTRATOFILENAME, value);
    }

    /**Gets the attribute value for the calculated attribute Contrato
     */
    public String getContrato() {
        return (String) getAttributeInternal(CONTRATO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Contrato
     */
    public void setContrato(String value) {
        setAttributeInternal(CONTRATO, value);
    }
}
