package xxqp.oracle.apps.ar.pdft.altafitec.masiplat.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OtrosProcesosTmpVORowImpl extends OAViewRowImpl {
    public static final int PROCESOID = 0;
    public static final int PROCESO = 1;
    public static final int SELECCIONAR = 2;
    public static final int PRECIO = 3;
    public static final int PRECIOPROTON = 4;

    /**This is the default constructor (do not remove)
     */
    public OtrosProcesosTmpVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute ProcesoId
     */
    public Number getProcesoId() {
        return (Number) getAttributeInternal(PROCESOID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProcesoId
     */
    public void setProcesoId(Number value) {
        setAttributeInternal(PROCESOID, value);
    }

    /**Gets the attribute value for the calculated attribute Proceso
     */
    public String getProceso() {
        return (String) getAttributeInternal(PROCESO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Proceso
     */
    public void setProceso(String value) {
        setAttributeInternal(PROCESO, value);
    }

    /**Gets the attribute value for the calculated attribute Seleccionar
     */
    public String getSeleccionar() {
        return (String) getAttributeInternal(SELECCIONAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Seleccionar
     */
    public void setSeleccionar(String value) {
        setAttributeInternal(SELECCIONAR, value);
    }

    /**Gets the attribute value for the calculated attribute Precio
     */
    public Number getPrecio() {
        return (Number) getAttributeInternal(PRECIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Precio
     */
    public void setPrecio(Number value) {
        setAttributeInternal(PRECIO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PROCESOID:
            return getProcesoId();
        case PROCESO:
            return getProceso();
        case SELECCIONAR:
            return getSeleccionar();
        case PRECIO:
            return getPrecio();
        case PRECIOPROTON:
            return getPrecioProton();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PROCESOID:
            setProcesoId((Number)value);
            return;
        case PROCESO:
            setProceso((String)value);
            return;
        case SELECCIONAR:
            setSeleccionar((String)value);
            return;
        case PRECIO:
            setPrecio((Number)value);
            return;
        case PRECIOPROTON:
            setPrecioProton((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute PrecioProton
     */
    public Number getPrecioProton() {
        return (Number) getAttributeInternal(PRECIOPROTON);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PrecioProton
     */
    public void setPrecioProton(Number value) {
        setAttributeInternal(PRECIOPROTON, value);
    }
}
