package xxqp.oracle.apps.ar.pdft.altafitec.masiplat.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import xxqp.oracle.apps.ar.pdft.altafitec.masiplat.schema.server.XxqpPdftMypGeneralEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxqpPdftMypGeneralVORowImpl extends OAViewRowImpl {
    public static final int ID = 0;
    public static final int MYPHEADERID = 1;
    public static final int IMPRESOR = 2;
    public static final int NOMBREPRODUCTO = 3;
    public static final int PUNTODERECOLECCION = 4;
    public static final int CONTACTOPARACIERRE = 5;
    public static final int PERIODICIDADC = 6;
    public static final int TIPOPRODUCTOC = 7;
    public static final int PESOPRODUCTOC = 8;
    public static final int DIMENSIONESC = 9;
    public static final int TIPOCOMISIONC = 10;
    public static final int SEFACTURAC = 11;
    public static final int FORMATOPARACIERREC = 12;
    public static final int DIASHABILESPAGO = 13;
    public static final int DIASRECEPCIONFATURACION = 14;
    public static final int REQUIEREVOBOC = 15;
    public static final int TIPOVOBO = 16;
    public static final int TIPODEENTREGAC = 17;
    public static final int POLITICADEENTREGAC = 18;
    public static final int CREATEDBY = 19;
    public static final int CREATIONDATE = 20;
    public static final int LASTUPDATEDBY = 21;
    public static final int LASTUPDATEDATE = 22;
    public static final int LASTUPDATELOGIN = 23;
    public static final int ATTRIBUTECATEGORY = 24;
    public static final int ATTRIBUTE1 = 25;
    public static final int ATTRIBUTE2 = 26;
    public static final int ATTRIBUTE3 = 27;
    public static final int ATTRIBUTE4 = 28;
    public static final int ATTRIBUTE5 = 29;
    public static final int VOLUMENAPROX = 30;
    public static final int DOMINGO = 31;
    public static final int JUEVES = 32;
    public static final int LUNES = 33;
    public static final int MARTES = 34;
    public static final int MIERCOLES = 35;
    public static final int SABADO = 36;
    public static final int VIERNES = 37;
    public static final int ACUSEC = 38;
    public static final int ORDINARIOC = 39;
    public static final int SEMIACUSEC = 40;

    /**This is the default constructor (do not remove)
     */
    public XxqpPdftMypGeneralVORowImpl() {
    }

    /**Gets XxqpPdftMypGeneralEO entity object.
     */
    public XxqpPdftMypGeneralEOImpl getXxqpPdftMypGeneralEO() {
        return (XxqpPdftMypGeneralEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ID using the alias name Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as attribute value for ID using the alias name Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for MYP_HEADER_ID using the alias name MypHeaderId
     */
    public Number getMypHeaderId() {
        return (Number) getAttributeInternal(MYPHEADERID);
    }

    /**Sets <code>value</code> as attribute value for MYP_HEADER_ID using the alias name MypHeaderId
     */
    public void setMypHeaderId(Number value) {
        setAttributeInternal(MYPHEADERID, value);
    }

    /**Gets the attribute value for IMPRESOR using the alias name Impresor
     */
    public String getImpresor() {
        return (String) getAttributeInternal(IMPRESOR);
    }

    /**Sets <code>value</code> as attribute value for IMPRESOR using the alias name Impresor
     */
    public void setImpresor(String value) {
        setAttributeInternal(IMPRESOR, value);
    }

    /**Gets the attribute value for NOMBRE_PRODUCTO using the alias name NombreProducto
     */
    public String getNombreProducto() {
        return (String) getAttributeInternal(NOMBREPRODUCTO);
    }

    /**Sets <code>value</code> as attribute value for NOMBRE_PRODUCTO using the alias name NombreProducto
     */
    public void setNombreProducto(String value) {
        setAttributeInternal(NOMBREPRODUCTO, value);
    }


    /**Gets the attribute value for PUNTO_DE_RECOLECCION using the alias name PuntoDeRecoleccion
     */
    public String getPuntoDeRecoleccion() {
        return (String) getAttributeInternal(PUNTODERECOLECCION);
    }

    /**Sets <code>value</code> as attribute value for PUNTO_DE_RECOLECCION using the alias name PuntoDeRecoleccion
     */
    public void setPuntoDeRecoleccion(String value) {
        setAttributeInternal(PUNTODERECOLECCION, value);
    }

    /**Gets the attribute value for CONTACTO_PARA_CIERRE using the alias name ContactoParaCierre
     */
    public String getContactoParaCierre() {
        return (String) getAttributeInternal(CONTACTOPARACIERRE);
    }

    /**Sets <code>value</code> as attribute value for CONTACTO_PARA_CIERRE using the alias name ContactoParaCierre
     */
    public void setContactoParaCierre(String value) {
        setAttributeInternal(CONTACTOPARACIERRE, value);
    }

    /**Gets the attribute value for PERIODICIDAD_C using the alias name PeriodicidadC
     */
    public String getPeriodicidadC() {
        return (String) getAttributeInternal(PERIODICIDADC);
    }

    /**Sets <code>value</code> as attribute value for PERIODICIDAD_C using the alias name PeriodicidadC
     */
    public void setPeriodicidadC(String value) {
        setAttributeInternal(PERIODICIDADC, value);
    }

    /**Gets the attribute value for TIPO_PRODUCTO_C using the alias name TipoProductoC
     */
    public String getTipoProductoC() {
        return (String) getAttributeInternal(TIPOPRODUCTOC);
    }

    /**Sets <code>value</code> as attribute value for TIPO_PRODUCTO_C using the alias name TipoProductoC
     */
    public void setTipoProductoC(String value) {
        setAttributeInternal(TIPOPRODUCTOC, value);
    }

    /**Gets the attribute value for PESO_PRODUCTO_C using the alias name PesoProductoC
     */
    public String getPesoProductoC() {
        return (String) getAttributeInternal(PESOPRODUCTOC);
    }

    /**Sets <code>value</code> as attribute value for PESO_PRODUCTO_C using the alias name PesoProductoC
     */
    public void setPesoProductoC(String value) {
        setAttributeInternal(PESOPRODUCTOC, value);
    }

    /**Gets the attribute value for DIMENSIONES_C using the alias name DimensionesC
     */
    public String getDimensionesC() {
        return (String) getAttributeInternal(DIMENSIONESC);
    }

    /**Sets <code>value</code> as attribute value for DIMENSIONES_C using the alias name DimensionesC
     */
    public void setDimensionesC(String value) {
        setAttributeInternal(DIMENSIONESC, value);
    }

    /**Gets the attribute value for TIPO_COMISION_C using the alias name TipoComisionC
     */
    public String getTipoComisionC() {
        return (String) getAttributeInternal(TIPOCOMISIONC);
    }

    /**Sets <code>value</code> as attribute value for TIPO_COMISION_C using the alias name TipoComisionC
     */
    public void setTipoComisionC(String value) {
        setAttributeInternal(TIPOCOMISIONC, value);
    }

    /**Gets the attribute value for SE_FACTURA_C using the alias name SeFacturaC
     */
    public String getSeFacturaC() {
        return (String) getAttributeInternal(SEFACTURAC);
    }

    /**Sets <code>value</code> as attribute value for SE_FACTURA_C using the alias name SeFacturaC
     */
    public void setSeFacturaC(String value) {
        setAttributeInternal(SEFACTURAC, value);
    }

    /**Gets the attribute value for FORMATO_PARA_CIERRE_C using the alias name FormatoParaCierreC
     */
    public String getFormatoParaCierreC() {
        return (String) getAttributeInternal(FORMATOPARACIERREC);
    }

    /**Sets <code>value</code> as attribute value for FORMATO_PARA_CIERRE_C using the alias name FormatoParaCierreC
     */
    public void setFormatoParaCierreC(String value) {
        setAttributeInternal(FORMATOPARACIERREC, value);
    }

    /**Gets the attribute value for DIAS_HABILES_PAGO using the alias name DiasHabilesPago
     */
    public String getDiasHabilesPago() {
        return (String) getAttributeInternal(DIASHABILESPAGO);
    }

    /**Sets <code>value</code> as attribute value for DIAS_HABILES_PAGO using the alias name DiasHabilesPago
     */
    public void setDiasHabilesPago(String value) {
        setAttributeInternal(DIASHABILESPAGO, value);
    }

    /**Gets the attribute value for DIAS_RECEPCION_FATURACION using the alias name DiasRecepcionFaturacion
     */
    public String getDiasRecepcionFaturacion() {
        return (String) getAttributeInternal(DIASRECEPCIONFATURACION);
    }

    /**Sets <code>value</code> as attribute value for DIAS_RECEPCION_FATURACION using the alias name DiasRecepcionFaturacion
     */
    public void setDiasRecepcionFaturacion(String value) {
        setAttributeInternal(DIASRECEPCIONFATURACION, value);
    }

    /**Gets the attribute value for REQUIERE_VOBO_C using the alias name RequiereVoboC
     */
    public String getRequiereVoboC() {
        return (String) getAttributeInternal(REQUIEREVOBOC);
    }

    /**Sets <code>value</code> as attribute value for REQUIERE_VOBO_C using the alias name RequiereVoboC
     */
    public void setRequiereVoboC(String value) {
        setAttributeInternal(REQUIEREVOBOC, value);
    }

    /**Gets the attribute value for TIPO_VOBO using the alias name TipoVobo
     */
    public String getTipoVobo() {
        return (String) getAttributeInternal(TIPOVOBO);
    }

    /**Sets <code>value</code> as attribute value for TIPO_VOBO using the alias name TipoVobo
     */
    public void setTipoVobo(String value) {
        setAttributeInternal(TIPOVOBO, value);
    }

    /**Gets the attribute value for TIPO_DE_ENTREGA_C using the alias name TipoDeEntregaC
     */
    public String getTipoDeEntregaC() {
        return (String) getAttributeInternal(TIPODEENTREGAC);
    }

    /**Sets <code>value</code> as attribute value for TIPO_DE_ENTREGA_C using the alias name TipoDeEntregaC
     */
    public void setTipoDeEntregaC(String value) {
        setAttributeInternal(TIPODEENTREGAC, value);
    }

    /**Gets the attribute value for POLITICA_DE_ENTREGA_C using the alias name PoliticaDeEntregaC
     */
    public String getPoliticaDeEntregaC() {
        return (String) getAttributeInternal(POLITICADEENTREGAC);
    }

    /**Sets <code>value</code> as attribute value for POLITICA_DE_ENTREGA_C using the alias name PoliticaDeEntregaC
     */
    public void setPoliticaDeEntregaC(String value) {
        setAttributeInternal(POLITICADEENTREGAC, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case MYPHEADERID:
            return getMypHeaderId();
        case IMPRESOR:
            return getImpresor();
        case NOMBREPRODUCTO:
            return getNombreProducto();
        case PUNTODERECOLECCION:
            return getPuntoDeRecoleccion();
        case CONTACTOPARACIERRE:
            return getContactoParaCierre();
        case PERIODICIDADC:
            return getPeriodicidadC();
        case TIPOPRODUCTOC:
            return getTipoProductoC();
        case PESOPRODUCTOC:
            return getPesoProductoC();
        case DIMENSIONESC:
            return getDimensionesC();
        case TIPOCOMISIONC:
            return getTipoComisionC();
        case SEFACTURAC:
            return getSeFacturaC();
        case FORMATOPARACIERREC:
            return getFormatoParaCierreC();
        case DIASHABILESPAGO:
            return getDiasHabilesPago();
        case DIASRECEPCIONFATURACION:
            return getDiasRecepcionFaturacion();
        case REQUIEREVOBOC:
            return getRequiereVoboC();
        case TIPOVOBO:
            return getTipoVobo();
        case TIPODEENTREGAC:
            return getTipoDeEntregaC();
        case POLITICADEENTREGAC:
            return getPoliticaDeEntregaC();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case VOLUMENAPROX:
            return getVolumenAprox();
        case DOMINGO:
            return getDomingo();
        case JUEVES:
            return getJueves();
        case LUNES:
            return getLunes();
        case MARTES:
            return getMartes();
        case MIERCOLES:
            return getMiercoles();
        case SABADO:
            return getSabado();
        case VIERNES:
            return getViernes();
        case ACUSEC:
            return getAcuseC();
        case ORDINARIOC:
            return getOrdinarioC();
        case SEMIACUSEC:
            return getSemiAcuseC();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case MYPHEADERID:
            setMypHeaderId((Number)value);
            return;
        case IMPRESOR:
            setImpresor((String)value);
            return;
        case NOMBREPRODUCTO:
            setNombreProducto((String)value);
            return;
        case PUNTODERECOLECCION:
            setPuntoDeRecoleccion((String)value);
            return;
        case CONTACTOPARACIERRE:
            setContactoParaCierre((String)value);
            return;
        case PERIODICIDADC:
            setPeriodicidadC((String)value);
            return;
        case TIPOPRODUCTOC:
            setTipoProductoC((String)value);
            return;
        case PESOPRODUCTOC:
            setPesoProductoC((String)value);
            return;
        case DIMENSIONESC:
            setDimensionesC((String)value);
            return;
        case TIPOCOMISIONC:
            setTipoComisionC((String)value);
            return;
        case SEFACTURAC:
            setSeFacturaC((String)value);
            return;
        case FORMATOPARACIERREC:
            setFormatoParaCierreC((String)value);
            return;
        case DIASHABILESPAGO:
            setDiasHabilesPago((String)value);
            return;
        case DIASRECEPCIONFATURACION:
            setDiasRecepcionFaturacion((String)value);
            return;
        case REQUIEREVOBOC:
            setRequiereVoboC((String)value);
            return;
        case TIPOVOBO:
            setTipoVobo((String)value);
            return;
        case TIPODEENTREGAC:
            setTipoDeEntregaC((String)value);
            return;
        case POLITICADEENTREGAC:
            setPoliticaDeEntregaC((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case VOLUMENAPROX:
            setVolumenAprox((Number)value);
            return;
        case DOMINGO:
            setDomingo((String)value);
            return;
        case JUEVES:
            setJueves((String)value);
            return;
        case LUNES:
            setLunes((String)value);
            return;
        case MARTES:
            setMartes((String)value);
            return;
        case MIERCOLES:
            setMiercoles((String)value);
            return;
        case SABADO:
            setSabado((String)value);
            return;
        case VIERNES:
            setViernes((String)value);
            return;
        case ACUSEC:
            setAcuseC((String)value);
            return;
        case ORDINARIOC:
            setOrdinarioC((String)value);
            return;
        case SEMIACUSEC:
            setSemiAcuseC((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for VOLUMEN_APROX using the alias name VolumenAprox
     */
    public Number getVolumenAprox() {
        return (Number) getAttributeInternal(VOLUMENAPROX);
    }

    /**Sets <code>value</code> as attribute value for VOLUMEN_APROX using the alias name VolumenAprox
     */
    public void setVolumenAprox(Number value) {
        setAttributeInternal(VOLUMENAPROX, value);
    }

    /**Gets the attribute value for DOMINGO using the alias name Domingo
     */
    public String getDomingo() {
        return (String) getAttributeInternal(DOMINGO);
    }

    /**Sets <code>value</code> as attribute value for DOMINGO using the alias name Domingo
     */
    public void setDomingo(String value) {
        setAttributeInternal(DOMINGO, value);
    }

    /**Gets the attribute value for JUEVES using the alias name Jueves
     */
    public String getJueves() {
        return (String) getAttributeInternal(JUEVES);
    }

    /**Sets <code>value</code> as attribute value for JUEVES using the alias name Jueves
     */
    public void setJueves(String value) {
        setAttributeInternal(JUEVES, value);
    }

    /**Gets the attribute value for LUNES using the alias name Lunes
     */
    public String getLunes() {
        return (String) getAttributeInternal(LUNES);
    }

    /**Sets <code>value</code> as attribute value for LUNES using the alias name Lunes
     */
    public void setLunes(String value) {
        setAttributeInternal(LUNES, value);
    }

    /**Gets the attribute value for MARTES using the alias name Martes
     */
    public String getMartes() {
        return (String) getAttributeInternal(MARTES);
    }

    /**Sets <code>value</code> as attribute value for MARTES using the alias name Martes
     */
    public void setMartes(String value) {
        setAttributeInternal(MARTES, value);
    }

    /**Gets the attribute value for MIERCOLES using the alias name Miercoles
     */
    public String getMiercoles() {
        return (String) getAttributeInternal(MIERCOLES);
    }

    /**Sets <code>value</code> as attribute value for MIERCOLES using the alias name Miercoles
     */
    public void setMiercoles(String value) {
        setAttributeInternal(MIERCOLES, value);
    }

    /**Gets the attribute value for SABADO using the alias name Sabado
     */
    public String getSabado() {
        return (String) getAttributeInternal(SABADO);
    }

    /**Sets <code>value</code> as attribute value for SABADO using the alias name Sabado
     */
    public void setSabado(String value) {
        setAttributeInternal(SABADO, value);
    }

    /**Gets the attribute value for VIERNES using the alias name Viernes
     */
    public String getViernes() {
        return (String) getAttributeInternal(VIERNES);
    }

    /**Sets <code>value</code> as attribute value for VIERNES using the alias name Viernes
     */
    public void setViernes(String value) {
        setAttributeInternal(VIERNES, value);
    }

    /**Gets the attribute value for ACUSE_C using the alias name AcuseC
     */
    public String getAcuseC() {
        return (String) getAttributeInternal(ACUSEC);
    }

    /**Sets <code>value</code> as attribute value for ACUSE_C using the alias name AcuseC
     */
    public void setAcuseC(String value) {
        setAttributeInternal(ACUSEC, value);
    }

    /**Gets the attribute value for ORDINARIO_C using the alias name OrdinarioC
     */
    public String getOrdinarioC() {
        return (String) getAttributeInternal(ORDINARIOC);
    }

    /**Sets <code>value</code> as attribute value for ORDINARIO_C using the alias name OrdinarioC
     */
    public void setOrdinarioC(String value) {
        setAttributeInternal(ORDINARIOC, value);
    }

    /**Gets the attribute value for SEMI_ACUSE_C using the alias name SemiAcuseC
     */
    public String getSemiAcuseC() {
        return (String) getAttributeInternal(SEMIACUSEC);
    }

    /**Sets <code>value</code> as attribute value for SEMI_ACUSE_C using the alias name SemiAcuseC
     */
    public void setSemiAcuseC(String value) {
        setAttributeInternal(SEMIACUSEC, value);
    }
}
