/* Formatted on 08/01/2021 09:20:44 a.m. (QP5 v5.149.1003.31008) */
CREATE OR REPLACE VIEW XXQP_HzPuiAcctSitesTableVO AS
SELECT *
  FROM (SELECT HzCustAccountSitesEOEx.CUST_ACCT_SITE_ID,
               HzCustAccountSitesEOEx.CUST_ACCOUNT_ID,
               HzCustAccountSitesEOEx.PARTY_SITE_ID,
               HzCustAccountSitesEOEx.LAST_UPDATE_DATE,
               HzCustAccountSitesEOEx.LAST_UPDATED_BY,
               HzCustAccountSitesEOEx.CREATION_DATE,
               HzCustAccountSitesEOEx.CREATED_BY,
               HzCustAccountSitesEOEx.LAST_UPDATE_LOGIN,
               HzCustAccountSitesEOEx.REQUEST_ID,
               HzCustAccountSitesEOEx.PROGRAM_APPLICATION_ID,
               HzCustAccountSitesEOEx.PROGRAM_ID,
               HzCustAccountSitesEOEx.PROGRAM_UPDATE_DATE,
               HzCustAccountSitesEOEx.WH_UPDATE_DATE,
               HzCustAccountSitesEOEx.ATTRIBUTE_CATEGORY,
               HzCustAccountSitesEOEx.ATTRIBUTE1,
               HzCustAccountSitesEOEx.ATTRIBUTE2,
               HzCustAccountSitesEOEx.ATTRIBUTE3,
               HzCustAccountSitesEOEx.ATTRIBUTE4,
               HzCustAccountSitesEOEx.ATTRIBUTE5,
               HzCustAccountSitesEOEx.ATTRIBUTE6,
               HzCustAccountSitesEOEx.ATTRIBUTE7,
               HzCustAccountSitesEOEx.ATTRIBUTE8,
               HzCustAccountSitesEOEx.ATTRIBUTE9,
               HzCustAccountSitesEOEx.ATTRIBUTE10,
               HzCustAccountSitesEOEx.ATTRIBUTE11,
               HzCustAccountSitesEOEx.ATTRIBUTE12,
               HzCustAccountSitesEOEx.ATTRIBUTE13,
               HzCustAccountSitesEOEx.ATTRIBUTE14,
               HzCustAccountSitesEOEx.ATTRIBUTE15,
               HzCustAccountSitesEOEx.ATTRIBUTE16,
               HzCustAccountSitesEOEx.ATTRIBUTE17,
               HzCustAccountSitesEOEx.ATTRIBUTE18,
               HzCustAccountSitesEOEx.ATTRIBUTE19,
               HzCustAccountSitesEOEx.ATTRIBUTE20,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE_CATEGORY,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE1,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE2,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE3,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE4,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE5,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE6,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE7,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE8,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE9,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE10,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE11,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE12,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE13,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE14,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE15,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE16,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE17,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE18,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE19,
               HzCustAccountSitesEOEx.GLOBAL_ATTRIBUTE20,
               HzCustAccountSitesEOEx.ORIG_SYSTEM_REFERENCE,
               HzCustAccountSitesEOEx.STATUS,
               HzCustAccountSitesEOEx.ORG_ID,
               HzCustAccountSitesEOEx.BILL_TO_FLAG,
               HzCustAccountSitesEOEx.MARKET_FLAG,
               HzCustAccountSitesEOEx.SHIP_TO_FLAG,
               HzCustAccountSitesEOEx.CUSTOMER_CATEGORY_CODE,
               HzCustAccountSitesEOEx.LANGUAGE,
               HzCustAccountSitesEOEx.KEY_ACCOUNT_FLAG,
               HzCustAccountSitesEOEx.TP_HEADER_ID,
               HzCustAccountSitesEOEx.ECE_TP_LOCATION_CODE,
               HzCustAccountSitesEOEx.SERVICE_TERRITORY_ID,
               HzCustAccountSitesEOEx.PRIMARY_SPECIALIST_ID,
               HzCustAccountSitesEOEx.SECONDARY_SPECIALIST_ID,
               HzCustAccountSitesEOEx.TERRITORY_ID,
               HzCustAccountSitesEOEx.ADDRESS_TEXT,
               HzCustAccountSitesEOEx.TERRITORY,
               HzCustAccountSitesEOEx.TRANSLATED_CUSTOMER_NAME,
               HzCustAccountSitesEOEx.OBJECT_VERSION_NUMBER,
               HzCustAccountSitesEOEx.CREATED_BY_MODULE,
               HzCustAccountSitesEOEx.APPLICATION_ID,
               ps.MAILSTOP,
               lc.COUNTRY,
               ps.PARTY_SITE_NAME,
               lc.ADDRESS_LINES_PHONETIC,
               ps.IDENTIFYING_ADDRESS_FLAG,
               hz_utility_v2pub.
                get_acct_site_purposes (
                  HzCustAccountSitesEOEx.CUST_ACCT_SITE_ID)
                  PURPOSES,
               lc.LOCATION_ID,
               HZ_UTILITY_V2PUB.GET_YAHOO_MAP_URL (lc.address1,
                                                   lc.address2,
                                                   lc.address3,
                                                   lc.address4,
                                                   lc.city,
                                                   lc.country,
                                                   lc.state,
                                                   lc.postal_code)
                  mapURL,
               terr.territory_short_name AS country_name,
               ou.name AS operating_unit,
               ps.party_site_number,
               HZ_UTILITY_V2PUB.
                get_lookupmeaning ('FND_LOOKUP_VALUES',
                                   'HZ_CPUI_REGISTRY_STATUS',
                                   HzCustAccountSitesEOEx.status)
                  AS SITE_STATUS_MEANING,
               lc.address1,
               lc.address2,
               lc.address3,
               lc.address4,
               lc.city,
               lc.state,
               lc.postal_code,
               lc.county,
               lc.province,
               HZ_FORMAT_PUB.format_address (lc.LOCATION_ID,
                                             NULL,
                                             NULL,
                                             ', ')
                  Address
          FROM HZ_CUST_ACCT_SITES HzCustAccountSitesEOEx,
               hz_party_sites ps,
               hz_locations lc,
               fnd_territories_vl terr,
               hr_operating_units ou
         WHERE   1=1 /**HzCustAccountSitesEOEx.CUST_ACCOUNT_ID = :1 **/
               AND HzCustAccountSitesEOEx.party_site_id = ps.party_site_id
               AND ps.location_id = lc.location_id
               AND terr.territory_code = lc.country
               AND HzCustAccountSitesEOEx.org_id = ou.organization_id) QRSLT
 WHERE (status = 'A'
        AND NOT EXISTS
                   (SELECT 'X'
                      FROM HZ_PARTY_SITES, HZ_CUST_ACCOUNTS
                     WHERE HZ_PARTY_SITES.party_site_id = QRSLT.party_site_id
                           AND HZ_CUST_ACCOUNTS.cust_account_id = QRSLT.cust_account_id
                           AND HZ_PARTY_SITES.party_id <>
                                  HZ_CUST_ACCOUNTS.party_id)
              )