 diana.uribe  (40 nuevo, 5 antiguo )
 eunise.serrano  (2 nuevo, 2 antiguo)
 noe.alcocer  (41 nuevo, 11 antiguo)
 

     
ALTER TABLE XXQP_PDFT_USUARIOS_RO MODIFY ID NOT NULL;

ALTER TABLE XXQP_PDFT_USUARIOS_RO ADD CONSTRAINT XXQP_PDFT_USUARIOS_RO_PK PRIMARY KEY (ID);

ALTER TABLE XXQP_PDFT_USUARIOS_RO MODIFY USUARIO NOT NULL;

ALTER TABLE XXQP_PDFT_USUARIOS_RO ADD CONSTRAINT XXQP_PDFT_USUARIOS_RO_U1  UNIQUE(USUARIO);