
select * from XXQP_PDFT_BPO_HEADER

select * from XXQP_PDFT_BPO_SERVICIO

/** FROM VARCHAR2(4000) TO CLOB **/
ALTER TABLE APPS.XXQP_PDFT_BPO_SERVICIO MODIFY OTROS CLOB; /** ORA-22858: modificacion no valida del tipo de dato **/

ALTER TABLE APPS.XXQP_PDFT_BPO_SERVICIO ADD OTROS_ILIM CLOB;

UPDATE XXQP_PDFT_BPO_SERVICIO
  SET OTROS_ILIM = OTROS
  WHERE OTROS IS NOT NULL

/** FROM VARCHAR2(4000) TO CLOB **/
ALTER TABLE APPS.XXQP_PDFT_BPO_SERVICIO MODIFY DIRECCION_BASE CLOB; /** ORA-22858: modificacion no valida del tipo de dato **/

ALTER TABLE APPS.XXQP_PDFT_BPO_SERVICIO ADD DIRECCION_BASE_ILIM CLOB;

UPDATE XXQP_PDFT_BPO_SERVICIO
  SET DIRECCION_BASE_ILIM = DIRECCION_BASE
  WHERE DIRECCION_BASE IS NOT NULL

/** FROM VARCHAR2(4000) TO CLOB **/
ALTER TABLE APPS.XXQP_PDFT_BPO_SERVICIO MODIFY OBSERVACIONES CLOB; /** ORA-22858: modificacion no valida del tipo de dato **/

ALTER TABLE APPS.XXQP_PDFT_BPO_SERVICIO ADD OBSERVACIONES_ILIM CLOB;

UPDATE XXQP_PDFT_BPO_SERVICIO
  SET OBSERVACIONES_ILIM = OBSERVACIONES
  WHERE OBSERVACIONES IS NOT NULL

/************************************************************/

SELECT * FROM XXQP_PDFT_BPO_REQUE_ADICIO
order by id desc

/** FROM VARCHAR2(4000) TO CLOB **/
ALTER TABLE APPS.XXQP_PDFT_BPO_REQUE_ADICIO MODIFY COMENTARIOS CLOB; /** ORA-22858: modificacion no valida del tipo de dato **/

ALTER TABLE APPS.XXQP_PDFT_BPO_REQUE_ADICIO ADD COMENTARIOS_ILIM CLOB;

UPDATE XXQP_PDFT_BPO_REQUE_ADICIO
  SET COMENTARIOS_ILIM = COMENTARIOS
  WHERE COMENTARIOS IS NOT NULL

/***********************************************************/



ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD FILE_NAME1 VARCHAR2(500 BYTE); 

ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD CONTENT_TYPE1 VARCHAR2(500 BYTE);      

ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD FILE1 BLOB;

ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD FILE_NAME2 VARCHAR2(500 BYTE);

ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD CONTENT_TYPE2 VARCHAR2(500 BYTE); 

ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD FILE2 BLOB; 

ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD FILE_NAME3 VARCHAR2(500 BYTE); 

ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD CONTENT_TYPE3 VARCHAR2(500 BYTE); 

ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD FILE3 BLOB;

ALTER TABLE APPS.XXQP_PDFT_BPO_HEADER ADD MODIF_REALIZ CLOB;  