ALTER TABLE APPS.XXQP_PDFT_CLIENTES_HEADER ADD  PARTY_ID NUMBER;

ALTER TABLE APPS.XXQP_PDFT_CLIENTES_HEADER ADD CONSTRAINT XXQP_PDFT_CLIENTES_HEADER_U2 UNIQUE(NOMBRE_CLIENTE);

ALTER TABLE APPS.XXQP_PDFT_CLIENTES_HEADER ADD CONSTRAINT XXQP_PDFT_CLIENTES_HEADER_U3 UNIQUE(PARTY_ID);

ALTER TABLE  APPS.XXQP_PDFT_CLIENTES_HEADER MODIFY PARTY_ID NUMBER NULL/*NOT NULL*/;

ALTER TABLE  APPS.XXQP_PDFT_CLIENTES_HEADER MODIFY NOMBRE_CLIENTE VARCHAR2(250 BYTE) NOT NULL;

ALTER TABLE APPS.XXQP_PDFT_CLIENTES_HEADER ADD  RFC VARCHAR2(50);

ALTER TABLE APPS.XXQP_PDFT_CLIENTES_HEADER ADD CONSTRAINT XXQP_PDFT_CLIENTES_HEADER_U4 UNIQUE(RFC);

ALTER TABLE APPS.XXQP_PDFT_CLIENTES_HEADER MODIFY  RFC VARCHAR2(50) NOT NULL;

ALTER TABLE APPS.XXQP_PDFT_CLIENTES_HEADER ADD RAZON_SOCIAL VARCHAR2(500 BYTE); 

ALTER TABLE APPS.XXQP_PDFT_CLIENTES_HEADER ADD CONSTRAINT XXQP_PDFT_CLIENTES_HEADER_U5 UNIQUE(RAZON_SOCIAL);

