package xxqp.oracle.apps.ar.pdft.altacliente.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CedulasTmpVORowImpl extends OAViewRowImpl {
    public static final int PCEDULAFILE = 0;
    public static final int SCEDULAFILE = 1;
    public static final int PCEDULAFILENAME = 2;
    public static final int SCEDULAFILENAME = 3;
    public static final int CEDULAP = 4;
    public static final int CEDULAS = 5;
    public static final int ENTREGAENQPPISREQUIRED = 6;

    /**This is the default constructor (do not remove)
     */
    public CedulasTmpVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute PcedulaFile
     */
    public BlobDomain getPcedulaFile() {
        return (BlobDomain) getAttributeInternal(PCEDULAFILE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PcedulaFile
     */
    public void setPcedulaFile(BlobDomain value) {
        System.out.println(" Comienza setPcedulaFile CedulasTmpVORowImpl");
        if(null!=value){
        this.setCedulaP("Y");
        }else{
            this.setCedulaP("N");
        }
        setAttributeInternal(PCEDULAFILE, value);
    }

    /**Gets the attribute value for the calculated attribute ScedulaFile
     */
    public BlobDomain getScedulaFile() {
        return (BlobDomain) getAttributeInternal(SCEDULAFILE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ScedulaFile
     */
    public void setScedulaFile(BlobDomain value) {
        System.out.println(" Comienza setScedulaFile CedulasTmpVORowImpl ");
        if(null!=value){
        this.setCedulaS("Y");
        }else{
            this.setCedulaS("N");
        }
        setAttributeInternal(SCEDULAFILE, value);
    }

    /**Gets the attribute value for the calculated attribute PcedulaFileName
     */
    public String getPcedulaFileName() {
        return (String) getAttributeInternal(PCEDULAFILENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PcedulaFileName
     */
    public void setPcedulaFileName(String value) {
        setAttributeInternal(PCEDULAFILENAME, value);
    }

    /**Gets the attribute value for the calculated attribute ScedulaFileName
     */
    public String getScedulaFileName() {
        return (String) getAttributeInternal(SCEDULAFILENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ScedulaFileName
     */
    public void setScedulaFileName(String value) {
        setAttributeInternal(SCEDULAFILENAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PCEDULAFILE:
            return getPcedulaFile();
        case SCEDULAFILE:
            return getScedulaFile();
        case PCEDULAFILENAME:
            return getPcedulaFileName();
        case SCEDULAFILENAME:
            return getScedulaFileName();
        case CEDULAP:
            return getCedulaP();
        case CEDULAS:
            return getCedulaS();
        case ENTREGAENQPPISREQUIRED:
            return getEntregaEnQpPisRequired();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case PCEDULAFILE:
            setPcedulaFile((BlobDomain)value);
            return;
        case SCEDULAFILE:
            setScedulaFile((BlobDomain)value);
            return;
        case PCEDULAFILENAME:
            setPcedulaFileName((String)value);
            return;
        case SCEDULAFILENAME:
            setScedulaFileName((String)value);
            return;
        case CEDULAP:
            setCedulaP((String)value);
            return;
        case CEDULAS:
            setCedulaS((String)value);
            return;
        case ENTREGAENQPPISREQUIRED:
            setEntregaEnQpPisRequired((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute CedulaP
     */
    public String getCedulaP() {
        return (String) getAttributeInternal(CEDULAP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CedulaP
     */
    public void setCedulaP(String value) {
        setAttributeInternal(CEDULAP, value);
    }

    /**Gets the attribute value for the calculated attribute CedulaS
     */
    public String getCedulaS() {
        return (String) getAttributeInternal(CEDULAS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CedulaS
     */
    public void setCedulaS(String value) {
        setAttributeInternal(CEDULAS, value);
    }

    /**Gets the attribute value for the calculated attribute EntregaEnQpPisRequired
     */
    public String getEntregaEnQpPisRequired() {
        return (String) getAttributeInternal(ENTREGAENQPPISREQUIRED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EntregaEnQpPisRequired
     */
    public void setEntregaEnQpPisRequired(String value) {
        setAttributeInternal(ENTREGAENQPPISREQUIRED, value);
    }
}
