package xxqp.oracle.apps.ar.pdft.altacliente.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DiasDeSemanaVORowImpl extends OAViewRowImpl {
    public static final int SELECCIONAR = 0;
    public static final int LUNES = 1;
    public static final int MARTES = 2;
    public static final int MIERCOLES = 3;
    public static final int JUEVES = 4;
    public static final int VIERNES = 5;
    public static final int SABADO = 6;
    public static final int DOMINGO = 7;

    /**This is the default constructor (do not remove)
     */
    public DiasDeSemanaVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Lunes
     */
    public String getLunes() {
        return (String) getAttributeInternal(LUNES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Lunes
     */
    public void setLunes(String value) {
        setAttributeInternal(LUNES, value);
    }

    /**Gets the attribute value for the calculated attribute Martes
     */
    public String getMartes() {
        return (String) getAttributeInternal(MARTES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Martes
     */
    public void setMartes(String value) {
        setAttributeInternal(MARTES, value);
    }

    /**Gets the attribute value for the calculated attribute Miercoles
     */
    public String getMiercoles() {
        return (String) getAttributeInternal(MIERCOLES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Miercoles
     */
    public void setMiercoles(String value) {
        setAttributeInternal(MIERCOLES, value);
    }

    /**Gets the attribute value for the calculated attribute Jueves
     */
    public String getJueves() {
        return (String) getAttributeInternal(JUEVES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Jueves
     */
    public void setJueves(String value) {
        setAttributeInternal(JUEVES, value);
    }

    /**Gets the attribute value for the calculated attribute Viernes
     */
    public String getViernes() {
        return (String) getAttributeInternal(VIERNES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Viernes
     */
    public void setViernes(String value) {
        setAttributeInternal(VIERNES, value);
    }

    /**Gets the attribute value for the calculated attribute Sabado
     */
    public String getSabado() {
        return (String) getAttributeInternal(SABADO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Sabado
     */
    public void setSabado(String value) {
        setAttributeInternal(SABADO, value);
    }

    /**Gets the attribute value for the calculated attribute Domingo
     */
    public String getDomingo() {
        return (String) getAttributeInternal(DOMINGO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Domingo
     */
    public void setDomingo(String value) {
        setAttributeInternal(DOMINGO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SELECCIONAR:
            return getSeleccionar();
        case LUNES:
            return getLunes();
        case MARTES:
            return getMartes();
        case MIERCOLES:
            return getMiercoles();
        case JUEVES:
            return getJueves();
        case VIERNES:
            return getViernes();
        case SABADO:
            return getSabado();
        case DOMINGO:
            return getDomingo();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SELECCIONAR:
            setSeleccionar((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Seleccionar
     */
    public String getSeleccionar() {
        return (String) getAttributeInternal(SELECCIONAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Seleccionar
     */
    public void setSeleccionar(String value) {
        setAttributeInternal(SELECCIONAR, value);
    }
}
