package xxqp.oracle.apps.ar.pdft.altafitec.masiplat.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxqpPdftMypHeaderEOImpl extends OAEntityImpl {
    public static final int ID = 0;
    public static final int NUMEROFT = 1;
    public static final int REV = 2;
    public static final int STATUS = 3;
    public static final int NUMEROFTREFERENCIA = 4;
    public static final int PARTYID = 5;
    public static final int PDFTCLIENTEHEADERID = 6;
    public static final int EMPRESAQUEFACTURAC = 7;
    public static final int UNIDADDENEGOCIOC = 8;
    public static final int FRECUENCIAFACTURACIONC = 9;
    public static final int CONTRATOFLAG = 10;
    public static final int CONTRATOFILENAME = 11;
    public static final int CONTRATOCONTENTTYPE = 12;
    public static final int CONTRATOFILE = 13;
    public static final int FECHAINICIALOPERACION = 14;
    public static final int CREATEDBY = 15;
    public static final int CREATIONDATE = 16;
    public static final int LASTUPDATEDBY = 17;
    public static final int LASTUPDATEDATE = 18;
    public static final int LASTUPDATELOGIN = 19;
    public static final int ATTRIBUTECATEGORY = 20;
    public static final int ATTRIBUTE1 = 21;
    public static final int ATTRIBUTE2 = 22;
    public static final int ATTRIBUTE3 = 23;
    public static final int ATTRIBUTE4 = 24;
    public static final int ATTRIBUTE5 = 25;
    public static final int EJECUTIVO = 26;
    public static final int ARTICULOORACLE = 27;
    public static final int XXQPPDFTMYPGENERALEO = 28;
    public static final int XXQPPDFTMYPCOBERTURAEO = 29;
    public static final int XXQPPDFTMYPDISTRIBUCIONEO = 30;
    public static final int XXQPPDFTMYPPROCESOSEO = 31;
    public static final int XXQPPDFTMYPREGNEGEO = 32;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public XxqpPdftMypHeaderEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxqp.oracle.apps.ar.pdft.altafitec.masiplat.schema.server.XxqpPdftMypHeaderEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for NumeroFt, using the alias name NumeroFt
     */
    public Number getNumeroFt() {
        return (Number)getAttributeInternal(NUMEROFT);
    }

    /**Sets <code>value</code> as the attribute value for NumeroFt
     */
    public void setNumeroFt(Number value) {
        setAttributeInternal(NUMEROFT, value);
    }

    /**Gets the attribute value for Rev, using the alias name Rev
     */
    public Number getRev() {
        return (Number)getAttributeInternal(REV);
    }

    /**Sets <code>value</code> as the attribute value for Rev
     */
    public void setRev(Number value) {
        setAttributeInternal(REV, value);
    }

    /**Gets the attribute value for Status, using the alias name Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for NumeroFtReferencia, using the alias name NumeroFtReferencia
     */
    public Number getNumeroFtReferencia() {
        return (Number)getAttributeInternal(NUMEROFTREFERENCIA);
    }

    /**Sets <code>value</code> as the attribute value for NumeroFtReferencia
     */
    public void setNumeroFtReferencia(Number value) {
        setAttributeInternal(NUMEROFTREFERENCIA, value);
    }

    /**Gets the attribute value for PartyId, using the alias name PartyId
     */
    public Number getPartyId() {
        return (Number)getAttributeInternal(PARTYID);
    }

    /**Sets <code>value</code> as the attribute value for PartyId
     */
    public void setPartyId(Number value) {
        setAttributeInternal(PARTYID, value);
    }

    /**Gets the attribute value for PdftClienteHeaderId, using the alias name PdftClienteHeaderId
     */
    public Number getPdftClienteHeaderId() {
        return (Number)getAttributeInternal(PDFTCLIENTEHEADERID);
    }

    /**Sets <code>value</code> as the attribute value for PdftClienteHeaderId
     */
    public void setPdftClienteHeaderId(Number value) {
        setAttributeInternal(PDFTCLIENTEHEADERID, value);
    }

    /**Gets the attribute value for EmpresaQueFacturaC, using the alias name EmpresaQueFacturaC
     */
    public String getEmpresaQueFacturaC() {
        return (String)getAttributeInternal(EMPRESAQUEFACTURAC);
    }

    /**Sets <code>value</code> as the attribute value for EmpresaQueFacturaC
     */
    public void setEmpresaQueFacturaC(String value) {
        setAttributeInternal(EMPRESAQUEFACTURAC, value);
    }

    /**Gets the attribute value for UnidadDeNegocioC, using the alias name UnidadDeNegocioC
     */
    public String getUnidadDeNegocioC() {
        return (String)getAttributeInternal(UNIDADDENEGOCIOC);
    }

    /**Sets <code>value</code> as the attribute value for UnidadDeNegocioC
     */
    public void setUnidadDeNegocioC(String value) {
        setAttributeInternal(UNIDADDENEGOCIOC, value);
    }

    /**Gets the attribute value for FrecuenciaFacturacionC, using the alias name FrecuenciaFacturacionC
     */
    public String getFrecuenciaFacturacionC() {
        return (String)getAttributeInternal(FRECUENCIAFACTURACIONC);
    }

    /**Sets <code>value</code> as the attribute value for FrecuenciaFacturacionC
     */
    public void setFrecuenciaFacturacionC(String value) {
        setAttributeInternal(FRECUENCIAFACTURACIONC, value);
    }

    /**Gets the attribute value for ContratoFlag, using the alias name ContratoFlag
     */
    public String getContratoFlag() {
        return (String)getAttributeInternal(CONTRATOFLAG);
    }

    /**Sets <code>value</code> as the attribute value for ContratoFlag
     */
    public void setContratoFlag(String value) {
        setAttributeInternal(CONTRATOFLAG, value);
    }

    /**Gets the attribute value for ContratoFileName, using the alias name ContratoFileName
     */
    public String getContratoFileName() {
        return (String)getAttributeInternal(CONTRATOFILENAME);
    }

    /**Sets <code>value</code> as the attribute value for ContratoFileName
     */
    public void setContratoFileName(String value) {
        setAttributeInternal(CONTRATOFILENAME, value);
    }

    /**Gets the attribute value for ContratoContentType, using the alias name ContratoContentType
     */
    public String getContratoContentType() {
        return (String)getAttributeInternal(CONTRATOCONTENTTYPE);
    }

    /**Sets <code>value</code> as the attribute value for ContratoContentType
     */
    public void setContratoContentType(String value) {
        setAttributeInternal(CONTRATOCONTENTTYPE, value);
    }

    /**Gets the attribute value for ContratoFile, using the alias name ContratoFile
     */
    public BlobDomain getContratoFile() {
        return (BlobDomain)getAttributeInternal(CONTRATOFILE);
    }

    /**Sets <code>value</code> as the attribute value for ContratoFile
     */
    public void setContratoFile(BlobDomain value) {
        setAttributeInternal(CONTRATOFILE, value);
    }

    /**Gets the attribute value for FechaInicialOperacion, using the alias name FechaInicialOperacion
     */
    public Date getFechaInicialOperacion() {
        return (Date)getAttributeInternal(FECHAINICIALOPERACION);
    }

    /**Sets <code>value</code> as the attribute value for FechaInicialOperacion
     */
    public void setFechaInicialOperacion(Date value) {
        setAttributeInternal(FECHAINICIALOPERACION, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case NUMEROFT:
            return getNumeroFt();
        case REV:
            return getRev();
        case STATUS:
            return getStatus();
        case NUMEROFTREFERENCIA:
            return getNumeroFtReferencia();
        case PARTYID:
            return getPartyId();
        case PDFTCLIENTEHEADERID:
            return getPdftClienteHeaderId();
        case EMPRESAQUEFACTURAC:
            return getEmpresaQueFacturaC();
        case UNIDADDENEGOCIOC:
            return getUnidadDeNegocioC();
        case FRECUENCIAFACTURACIONC:
            return getFrecuenciaFacturacionC();
        case CONTRATOFLAG:
            return getContratoFlag();
        case CONTRATOFILENAME:
            return getContratoFileName();
        case CONTRATOCONTENTTYPE:
            return getContratoContentType();
        case CONTRATOFILE:
            return getContratoFile();
        case FECHAINICIALOPERACION:
            return getFechaInicialOperacion();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case EJECUTIVO:
            return getEjecutivo();
        case ARTICULOORACLE:
            return getArticuloOracle();
        case XXQPPDFTMYPCOBERTURAEO:
            return getXxqpPdftMypCoberturaEO();
        case XXQPPDFTMYPDISTRIBUCIONEO:
            return getXxqpPdftMypDistribucionEO();
        case XXQPPDFTMYPGENERALEO:
            return getXxqpPdftMypGeneralEO();
        case XXQPPDFTMYPPROCESOSEO:
            return getXxqpPdftMypProcesosEO();
        case XXQPPDFTMYPREGNEGEO:
            return getXxqpPdftMypRegNegEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case NUMEROFT:
            setNumeroFt((Number)value);
            return;
        case REV:
            setRev((Number)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case NUMEROFTREFERENCIA:
            setNumeroFtReferencia((Number)value);
            return;
        case PARTYID:
            setPartyId((Number)value);
            return;
        case PDFTCLIENTEHEADERID:
            setPdftClienteHeaderId((Number)value);
            return;
        case EMPRESAQUEFACTURAC:
            setEmpresaQueFacturaC((String)value);
            return;
        case UNIDADDENEGOCIOC:
            setUnidadDeNegocioC((String)value);
            return;
        case FRECUENCIAFACTURACIONC:
            setFrecuenciaFacturacionC((String)value);
            return;
        case CONTRATOFLAG:
            setContratoFlag((String)value);
            return;
        case CONTRATOFILENAME:
            setContratoFileName((String)value);
            return;
        case CONTRATOCONTENTTYPE:
            setContratoContentType((String)value);
            return;
        case CONTRATOFILE:
            setContratoFile((BlobDomain)value);
            return;
        case FECHAINICIALOPERACION:
            setFechaInicialOperacion((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case EJECUTIVO:
            setEjecutivo((String)value);
            return;
        case ARTICULOORACLE:
            setArticuloOracle((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getXxqpPdftMypGeneralEO() {
        return (RowIterator)getAttributeInternal(XXQPPDFTMYPGENERALEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getXxqpPdftMypCoberturaEO() {
        return (RowIterator)getAttributeInternal(XXQPPDFTMYPCOBERTURAEO);
    }


    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getXxqpPdftMypDistribucionEO() {
        return (RowIterator)getAttributeInternal(XXQPPDFTMYPDISTRIBUCIONEO);
    }


    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getXxqpPdftMypProcesosEO() {
        return (RowIterator)getAttributeInternal(XXQPPDFTMYPPROCESOSEO);
    }

    /**Gets the attribute value for Ejecutivo, using the alias name Ejecutivo
     */
    public String getEjecutivo() {
        return (String)getAttributeInternal(EJECUTIVO);
    }

    /**Sets <code>value</code> as the attribute value for Ejecutivo
     */
    public void setEjecutivo(String value) {
        setAttributeInternal(EJECUTIVO, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getXxqpPdftMypRegNegEO() {
        return (RowIterator)getAttributeInternal(XXQPPDFTMYPREGNEGEO);
    }

    /**Gets the attribute value for ArticuloOracle, using the alias name ArticuloOracle
     */
    public String getArticuloOracle() {
        return (String)getAttributeInternal(ARTICULOORACLE);
    }

    /**Sets <code>value</code> as the attribute value for ArticuloOracle
     */
    public void setArticuloOracle(String value) {
        setAttributeInternal(ARTICULOORACLE, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }
}
