package xxqp.oracle.apps.ar.pdft.altacliente.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxqpPdftClientesPuntoRecoEOImpl extends OAEntityImpl {
    public static final int ID = 0;
    public static final int HEADERID = 1;
    public static final int PRIMENTREGAENQP = 2;
    public static final int PRIMNOMBRE = 3;
    public static final int PRIMCONTACTO = 4;
    public static final int PRIMDIRECCION = 5;
    public static final int PRIMDIA = 6;
    public static final int PRIMHORARIO = 7;
    public static final int SECENTREGAENQP = 8;
    public static final int SECNOMBRE = 9;
    public static final int SECCONTACTO = 10;
    public static final int SECDIRECCION = 11;
    public static final int SECDIA = 12;
    public static final int SECHORARIO = 13;
    public static final int CREATEDBY = 14;
    public static final int CREATIONDATE = 15;
    public static final int LASTUPDATEDBY = 16;
    public static final int LASTUPDATEDATE = 17;
    public static final int LASTUPDATELOGIN = 18;
    public static final int ATTRIBUTECATEGORY = 19;
    public static final int ATTRIBUTE1 = 20;
    public static final int ATTRIBUTE2 = 21;
    public static final int ATTRIBUTE3 = 22;
    public static final int ATTRIBUTE4 = 23;
    public static final int ATTRIBUTE5 = 24;
    public static final int XXQPPDFTCLIENTESHEADEREO = 25;
    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public XxqpPdftClientesPuntoRecoEOImpl() {
    }

    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxqp.oracle.apps.ar.pdft.altacliente.schema.server.XxqpPdftClientesPuntoRecoEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for HeaderId, using the alias name HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**Sets <code>value</code> as the attribute value for HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**Gets the attribute value for PrimEntregaEnQp, using the alias name PrimEntregaEnQp
     */
    public String getPrimEntregaEnQp() {
        return (String)getAttributeInternal(PRIMENTREGAENQP);
    }

    /**Sets <code>value</code> as the attribute value for PrimEntregaEnQp
     */
    public void setPrimEntregaEnQp(String value) {
        setAttributeInternal(PRIMENTREGAENQP, value);
    }

    /**Gets the attribute value for PrimNombre, using the alias name PrimNombre
     */
    public String getPrimNombre() {
        return (String)getAttributeInternal(PRIMNOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for PrimNombre
     */
    public void setPrimNombre(String value) {
        setAttributeInternal(PRIMNOMBRE, value);
    }

    /**Gets the attribute value for PrimContacto, using the alias name PrimContacto
     */
    public String getPrimContacto() {
        return (String)getAttributeInternal(PRIMCONTACTO);
    }

    /**Sets <code>value</code> as the attribute value for PrimContacto
     */
    public void setPrimContacto(String value) {
        setAttributeInternal(PRIMCONTACTO, value);
    }

    /**Gets the attribute value for PrimDireccion, using the alias name PrimDireccion
     */
    public String getPrimDireccion() {
        return (String)getAttributeInternal(PRIMDIRECCION);
    }

    /**Sets <code>value</code> as the attribute value for PrimDireccion
     */
    public void setPrimDireccion(String value) {
        setAttributeInternal(PRIMDIRECCION, value);
    }

    /**Gets the attribute value for PrimDia, using the alias name PrimDia
     */
    public String getPrimDia() {
        return (String)getAttributeInternal(PRIMDIA);
    }

    /**Sets <code>value</code> as the attribute value for PrimDia
     */
    public void setPrimDia(String value) {
        setAttributeInternal(PRIMDIA, value);
    }

    /**Gets the attribute value for PrimHorario, using the alias name PrimHorario
     */
    public String getPrimHorario() {
        return (String)getAttributeInternal(PRIMHORARIO);
    }

    /**Sets <code>value</code> as the attribute value for PrimHorario
     */
    public void setPrimHorario(String value) {
        setAttributeInternal(PRIMHORARIO, value);
    }

    /**Gets the attribute value for SecEntregaEnQp, using the alias name SecEntregaEnQp
     */
    public String getSecEntregaEnQp() {
        return (String)getAttributeInternal(SECENTREGAENQP);
    }

    /**Sets <code>value</code> as the attribute value for SecEntregaEnQp
     */
    public void setSecEntregaEnQp(String value) {
        setAttributeInternal(SECENTREGAENQP, value);
    }

    /**Gets the attribute value for SecNombre, using the alias name SecNombre
     */
    public String getSecNombre() {
        return (String)getAttributeInternal(SECNOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for SecNombre
     */
    public void setSecNombre(String value) {
        setAttributeInternal(SECNOMBRE, value);
    }

    /**Gets the attribute value for SecContacto, using the alias name SecContacto
     */
    public String getSecContacto() {
        return (String)getAttributeInternal(SECCONTACTO);
    }

    /**Sets <code>value</code> as the attribute value for SecContacto
     */
    public void setSecContacto(String value) {
        setAttributeInternal(SECCONTACTO, value);
    }

    /**Gets the attribute value for SecDireccion, using the alias name SecDireccion
     */
    public String getSecDireccion() {
        return (String)getAttributeInternal(SECDIRECCION);
    }

    /**Sets <code>value</code> as the attribute value for SecDireccion
     */
    public void setSecDireccion(String value) {
        setAttributeInternal(SECDIRECCION, value);
    }

    /**Gets the attribute value for SecDia, using the alias name SecDia
     */
    public String getSecDia() {
        return (String)getAttributeInternal(SECDIA);
    }

    /**Sets <code>value</code> as the attribute value for SecDia
     */
    public void setSecDia(String value) {
        setAttributeInternal(SECDIA, value);
    }

    /**Gets the attribute value for SecHorario, using the alias name SecHorario
     */
    public String getSecHorario() {
        return (String)getAttributeInternal(SECHORARIO);
    }

    /**Sets <code>value</code> as the attribute value for SecHorario
     */
    public void setSecHorario(String value) {
        setAttributeInternal(SECHORARIO, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case HEADERID:
            return getHeaderId();
        case PRIMENTREGAENQP:
            return getPrimEntregaEnQp();
        case PRIMNOMBRE:
            return getPrimNombre();
        case PRIMCONTACTO:
            return getPrimContacto();
        case PRIMDIRECCION:
            return getPrimDireccion();
        case PRIMDIA:
            return getPrimDia();
        case PRIMHORARIO:
            return getPrimHorario();
        case SECENTREGAENQP:
            return getSecEntregaEnQp();
        case SECNOMBRE:
            return getSecNombre();
        case SECCONTACTO:
            return getSecContacto();
        case SECDIRECCION:
            return getSecDireccion();
        case SECDIA:
            return getSecDia();
        case SECHORARIO:
            return getSecHorario();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case XXQPPDFTCLIENTESHEADEREO:
            return getXxqpPdftClientesHeaderEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case HEADERID:
            setHeaderId((Number)value);
            return;
        case PRIMENTREGAENQP:
            setPrimEntregaEnQp((String)value);
            return;
        case PRIMNOMBRE:
            setPrimNombre((String)value);
            return;
        case PRIMCONTACTO:
            setPrimContacto((String)value);
            return;
        case PRIMDIRECCION:
            setPrimDireccion((String)value);
            return;
        case PRIMDIA:
            setPrimDia((String)value);
            return;
        case PRIMHORARIO:
            setPrimHorario((String)value);
            return;
        case SECENTREGAENQP:
            setSecEntregaEnQp((String)value);
            return;
        case SECNOMBRE:
            setSecNombre((String)value);
            return;
        case SECCONTACTO:
            setSecContacto((String)value);
            return;
        case SECDIRECCION:
            setSecDireccion((String)value);
            return;
        case SECDIA:
            setSecDia((String)value);
            return;
        case SECHORARIO:
            setSecHorario((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity XxqpPdftClientesHeaderEOImpl
     */
    public XxqpPdftClientesHeaderEOImpl getXxqpPdftClientesHeaderEO() {
        return (XxqpPdftClientesHeaderEOImpl)getAttributeInternal(XXQPPDFTCLIENTESHEADEREO);
    }

    /**Sets <code>value</code> as the associated entity XxqpPdftClientesHeaderEOImpl
     */
    public void setXxqpPdftClientesHeaderEO(XxqpPdftClientesHeaderEOImpl value) {
        setAttributeInternal(XXQPPDFTCLIENTESHEADEREO, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }
}
