package xxqp.oracle.apps.ar.pdft.altacliente.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxqpPdftClientesHeaderEOImpl extends OAEntityImpl {
    public static final int ID = 0;
    public static final int NOMBRECLIENTE = 1;
    public static final int GIROEMPRESARIALC = 2;
    public static final int EMPRESAQUEFACTURAC = 3;
    public static final int TIPOOPERATIVOC = 4;
    public static final int TIPOADMINISTRATIVOC = 5;
    public static final int TIPOCOMERCIALC = 6;
    public static final int COMENTARIOS = 7;
    public static final int CREATEDBY = 8;
    public static final int CREATIONDATE = 9;
    public static final int LASTUPDATEDBY = 10;
    public static final int LASTUPDATEDATE = 11;
    public static final int LASTUPDATELOGIN = 12;
    public static final int ATTRIBUTECATEGORY = 13;
    public static final int ATTRIBUTE1 = 14;
    public static final int ATTRIBUTE2 = 15;
    public static final int ATTRIBUTE3 = 16;
    public static final int ATTRIBUTE4 = 17;
    public static final int ATTRIBUTE5 = 18;
    public static final int PARTYID = 19;
    public static final int RFC = 20;
    public static final int RAZONSOCIAL = 21;
    public static final int XXQPPDFTCLIENTESDIRFISCALEO = 22;
    public static final int XXQPPDFTCLIENTESPUNTORECOEO = 23;
    public static final int XXQPPDFTCLIENTESCONTACTOSEO = 24;
    public static final int XXQPPDFTCLIENTESFACTPAGEO = 25;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public XxqpPdftClientesHeaderEOImpl()
  {
  }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxqp.oracle.apps.ar.pdft.altacliente.schema.server.XxqpPdftClientesHeaderEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList)
  {
    super.create(attributeList);
  }

  /**Add entity remove logic in this method.
   */
  public void remove()
  {
    super.remove();
  }

  /**Add Entity validation code in this method.
   */
  protected void validateEntity()
  {
    super.validateEntity();
  }

  /**Gets the attribute value for Id, using the alias name Id
   */
  public Number getId()
  {
    return (Number)getAttributeInternal(ID);
  }

  /**Sets <code>value</code> as the attribute value for Id
   */
  public void setId(Number value)
  {
    setAttributeInternal(ID, value);
  }

  /**Gets the attribute value for NombreCliente, using the alias name NombreCliente
   */
  public String getNombreCliente()
  {
    return (String)getAttributeInternal(NOMBRECLIENTE);
  }

  /**Sets <code>value</code> as the attribute value for NombreCliente
   */
  public void setNombreCliente(String value)
  {
    setAttributeInternal(NOMBRECLIENTE, value);
  }

  /**Gets the attribute value for GiroEmpresarialC, using the alias name GiroEmpresarialC
   */
  public String getGiroEmpresarialC()
  {
    return (String)getAttributeInternal(GIROEMPRESARIALC);
  }

  /**Sets <code>value</code> as the attribute value for GiroEmpresarialC
   */
  public void setGiroEmpresarialC(String value)
  {
    setAttributeInternal(GIROEMPRESARIALC, value);
  }


    /**Gets the attribute value for EmpresaQueFacturaC, using the alias name EmpresaQueFacturaC
     */
  public String getEmpresaQueFacturaC()
  {
    return (String)getAttributeInternal(EMPRESAQUEFACTURAC);
  }

  /**Sets <code>value</code> as the attribute value for EmpresaQueFacturaC
   */
  public void setEmpresaQueFacturaC(String value)
  {
    setAttributeInternal(EMPRESAQUEFACTURAC, value);
  }


    /**Gets the attribute value for TipoOperativoC, using the alias name TipoOperativoC
     */
  public String getTipoOperativoC()
  {
    return (String)getAttributeInternal(TIPOOPERATIVOC);
  }

  /**Sets <code>value</code> as the attribute value for TipoOperativoC
   */
  public void setTipoOperativoC(String value)
  {
    setAttributeInternal(TIPOOPERATIVOC, value);
  }


    /**Gets the attribute value for TipoAdministrativoC, using the alias name TipoAdministrativoC
     */
  public String getTipoAdministrativoC()
  {
    return (String)getAttributeInternal(TIPOADMINISTRATIVOC);
  }

  /**Sets <code>value</code> as the attribute value for TipoAdministrativoC
   */
  public void setTipoAdministrativoC(String value)
  {
    setAttributeInternal(TIPOADMINISTRATIVOC, value);
  }


    /**Gets the attribute value for TipoComercialC, using the alias name TipoComercialC
     */
  public String getTipoComercialC()
  {
    return (String)getAttributeInternal(TIPOCOMERCIALC);
  }

  /**Sets <code>value</code> as the attribute value for TipoComercialC
   */
  public void setTipoComercialC(String value)
  {
    setAttributeInternal(TIPOCOMERCIALC, value);
  }


    /**Gets the attribute value for Comentarios, using the alias name Comentarios
     */
  public String getComentarios()
  {
    return (String)getAttributeInternal(COMENTARIOS);
  }

  /**Sets <code>value</code> as the attribute value for Comentarios
   */
  public void setComentarios(String value)
  {
    setAttributeInternal(COMENTARIOS, value);
  }

  /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
   */
  public Number getCreatedBy()
  {
    return (Number)getAttributeInternal(CREATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for CreatedBy
   */
  public void setCreatedBy(Number value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**Gets the attribute value for CreationDate, using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**Sets <code>value</code> as the attribute value for CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
   */
  public Number getLastUpdatedBy()
  {
    return (Number)getAttributeInternal(LASTUPDATEDBY);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdatedBy
   */
  public void setLastUpdatedBy(Number value)
  {
    setAttributeInternal(LASTUPDATEDBY, value);
  }

  /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
   */
  public Date getLastUpdateDate()
  {
    return (Date)getAttributeInternal(LASTUPDATEDATE);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateDate
   */
  public void setLastUpdateDate(Date value)
  {
    setAttributeInternal(LASTUPDATEDATE, value);
  }

  /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
   */
  public Number getLastUpdateLogin()
  {
    return (Number)getAttributeInternal(LASTUPDATELOGIN);
  }

  /**Sets <code>value</code> as the attribute value for LastUpdateLogin
   */
  public void setLastUpdateLogin(Number value)
  {
    setAttributeInternal(LASTUPDATELOGIN, value);
  }

  /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
   */
  public String getAttributeCategory()
  {
    return (String)getAttributeInternal(ATTRIBUTECATEGORY);
  }

  /**Sets <code>value</code> as the attribute value for AttributeCategory
   */
  public void setAttributeCategory(String value)
  {
    setAttributeInternal(ATTRIBUTECATEGORY, value);
  }

  /**Gets the attribute value for Attribute1, using the alias name Attribute1
   */
  public String getAttribute1()
  {
    return (String)getAttributeInternal(ATTRIBUTE1);
  }

  /**Sets <code>value</code> as the attribute value for Attribute1
   */
  public void setAttribute1(String value)
  {
    setAttributeInternal(ATTRIBUTE1, value);
  }

  /**Gets the attribute value for Attribute2, using the alias name Attribute2
   */
  public String getAttribute2()
  {
    return (String)getAttributeInternal(ATTRIBUTE2);
  }

  /**Sets <code>value</code> as the attribute value for Attribute2
   */
  public void setAttribute2(String value)
  {
    setAttributeInternal(ATTRIBUTE2, value);
  }

  /**Gets the attribute value for Attribute3, using the alias name Attribute3
   */
  public String getAttribute3()
  {
    return (String)getAttributeInternal(ATTRIBUTE3);
  }

  /**Sets <code>value</code> as the attribute value for Attribute3
   */
  public void setAttribute3(String value)
  {
    setAttributeInternal(ATTRIBUTE3, value);
  }

  /**Gets the attribute value for Attribute4, using the alias name Attribute4
   */
  public String getAttribute4()
  {
    return (String)getAttributeInternal(ATTRIBUTE4);
  }

  /**Sets <code>value</code> as the attribute value for Attribute4
   */
  public void setAttribute4(String value)
  {
    setAttributeInternal(ATTRIBUTE4, value);
  }

  /**Gets the attribute value for Attribute5, using the alias name Attribute5
   */
  public String getAttribute5()
  {
    return (String)getAttributeInternal(ATTRIBUTE5);
  }

  /**Sets <code>value</code> as the attribute value for Attribute5
   */
  public void setAttribute5(String value)
  {
    setAttributeInternal(ATTRIBUTE5, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index, 
                                         AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case ID:
            return getId();
        case NOMBRECLIENTE:
            return getNombreCliente();
        case GIROEMPRESARIALC:
            return getGiroEmpresarialC();
        case EMPRESAQUEFACTURAC:
            return getEmpresaQueFacturaC();
        case TIPOOPERATIVOC:
            return getTipoOperativoC();
        case TIPOADMINISTRATIVOC:
            return getTipoAdministrativoC();
        case TIPOCOMERCIALC:
            return getTipoComercialC();
        case COMENTARIOS:
            return getComentarios();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case PARTYID:
            return getPartyId();
        case RFC:
            return getRfc();
        case RAZONSOCIAL:
            return getRazonSocial();
        case XXQPPDFTCLIENTESCONTACTOSEO:
            return getXxqpPdftClientesContactosEO();
        case XXQPPDFTCLIENTESDIRFISCALEO:
            return getXxqpPdftClientesDirFiscalEO();
        case XXQPPDFTCLIENTESFACTPAGEO:
            return getXxqpPdftClientesFactPagEO();
        case XXQPPDFTCLIENTESPUNTORECOEO:
            return getXxqpPdftClientesPuntoRecoEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value, 
                                       AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case NOMBRECLIENTE:
            setNombreCliente((String)value);
            return;
        case GIROEMPRESARIALC:
            setGiroEmpresarialC((String)value);
            return;
        case EMPRESAQUEFACTURAC:
            setEmpresaQueFacturaC((String)value);
            return;
        case TIPOOPERATIVOC:
            setTipoOperativoC((String)value);
            return;
        case TIPOADMINISTRATIVOC:
            setTipoAdministrativoC((String)value);
            return;
        case TIPOCOMERCIALC:
            setTipoComercialC((String)value);
            return;
        case COMENTARIOS:
            setComentarios((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case PARTYID:
            setPartyId((Number)value);
            return;
        case RFC:
            setRfc((String)value);
            return;
        case RAZONSOCIAL:
            setRazonSocial((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getXxqpPdftClientesDirFiscalEO() {
        return (RowIterator)getAttributeInternal(XXQPPDFTCLIENTESDIRFISCALEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getXxqpPdftClientesPuntoRecoEO() {
        return (RowIterator)getAttributeInternal(XXQPPDFTCLIENTESPUNTORECOEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getXxqpPdftClientesContactosEO() {
        return (RowIterator)getAttributeInternal(XXQPPDFTCLIENTESCONTACTOSEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getXxqpPdftClientesFactPagEO() {
        return (RowIterator)getAttributeInternal(XXQPPDFTCLIENTESFACTPAGEO);
    }

    /**Gets the attribute value for PartyId, using the alias name PartyId
     */
    public Number getPartyId() {
        return (Number)getAttributeInternal(PARTYID);
    }

    /**Sets <code>value</code> as the attribute value for PartyId
     */
    public void setPartyId(Number value) {
        setAttributeInternal(PARTYID, value);
    }

    /**Gets the attribute value for Rfc, using the alias name Rfc
     */
    public String getRfc() {
        return (String)getAttributeInternal(RFC);
    }

    /**Sets <code>value</code> as the attribute value for Rfc
     */
    public void setRfc(String value) {
        setAttributeInternal(RFC, value);
    }


    /**Gets the attribute value for RazonSocial, using the alias name RazonSocial
     */
    public String getRazonSocial() {
        return (String)getAttributeInternal(RAZONSOCIAL);
    }

    /**Sets <code>value</code> as the attribute value for RazonSocial
     */
    public void setRazonSocial(String value) {
        setAttributeInternal(RAZONSOCIAL, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }
}
