package xxqp.oracle.apps.ar.pdft.altacliente.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxqpPdftClientesContactosEOImpl extends OAEntityImpl {
    public static final int ID = 0;
    public static final int HEADERID = 1;
    public static final int TIPOCONTACTO = 2;
    public static final int NOMBRE = 3;
    public static final int DIRECCION = 4;
    public static final int TELEFONO = 5;
    public static final int CORREOELECTRONICO = 6;
    public static final int PUESTO = 7;
    public static final int CREATEDBY = 8;
    public static final int CREATIONDATE = 9;
    public static final int LASTUPDATEDBY = 10;
    public static final int LASTUPDATEDATE = 11;
    public static final int LASTUPDATELOGIN = 12;
    public static final int ATTRIBUTECATEGORY = 13;
    public static final int ATTRIBUTE1 = 14;
    public static final int ATTRIBUTE2 = 15;
    public static final int ATTRIBUTE3 = 16;
    public static final int ATTRIBUTE4 = 17;
    public static final int ATTRIBUTE5 = 18;
    public static final int NUMEROCELULAR = 19;
    public static final int CUMPLEANIOS = 20;
    public static final int XXQPPDFTCLIENTESHEADEREO = 21;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public XxqpPdftClientesContactosEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxqp.oracle.apps.ar.pdft.altacliente.schema.server.XxqpPdftClientesContactosEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for Id, using the alias name Id
     */
    public Number getId() {
        return (Number)getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for HeaderId, using the alias name HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**Sets <code>value</code> as the attribute value for HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**Gets the attribute value for TipoContacto, using the alias name TipoContacto
     */
    public String getTipoContacto() {
        return (String)getAttributeInternal(TIPOCONTACTO);
    }

    /**Sets <code>value</code> as the attribute value for TipoContacto
     */
    public void setTipoContacto(String value) {
        setAttributeInternal(TIPOCONTACTO, value);
    }

    /**Gets the attribute value for Nombre, using the alias name Nombre
     */
    public String getNombre() {
        return (String)getAttributeInternal(NOMBRE);
    }

    /**Sets <code>value</code> as the attribute value for Nombre
     */
    public void setNombre(String value) {
        setAttributeInternal(NOMBRE, value);
    }

    /**Gets the attribute value for Direccion, using the alias name Direccion
     */
    public String getDireccion() {
        return (String)getAttributeInternal(DIRECCION);
    }

    /**Sets <code>value</code> as the attribute value for Direccion
     */
    public void setDireccion(String value) {
        setAttributeInternal(DIRECCION, value);
    }

    /**Gets the attribute value for Telefono, using the alias name Telefono
     */
    public String getTelefono() {
        return (String)getAttributeInternal(TELEFONO);
    }

    /**Sets <code>value</code> as the attribute value for Telefono
     */
    public void setTelefono(String value) {
        setAttributeInternal(TELEFONO, value);
    }

    /**Gets the attribute value for CorreoElectronico, using the alias name CorreoElectronico
     */
    public String getCorreoElectronico() {
        return (String)getAttributeInternal(CORREOELECTRONICO);
    }

    /**Sets <code>value</code> as the attribute value for CorreoElectronico
     */
    public void setCorreoElectronico(String value) {
        setAttributeInternal(CORREOELECTRONICO, value);
    }

    /**Gets the attribute value for Puesto, using the alias name Puesto
     */
    public String getPuesto() {
        return (String)getAttributeInternal(PUESTO);
    }

    /**Sets <code>value</code> as the attribute value for Puesto
     */
    public void setPuesto(String value) {
        setAttributeInternal(PUESTO, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case HEADERID:
            return getHeaderId();
        case TIPOCONTACTO:
            return getTipoContacto();
        case NOMBRE:
            return getNombre();
        case DIRECCION:
            return getDireccion();
        case TELEFONO:
            return getTelefono();
        case CORREOELECTRONICO:
            return getCorreoElectronico();
        case PUESTO:
            return getPuesto();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case NUMEROCELULAR:
            return getNumeroCelular();
        case CUMPLEANIOS:
            return getCumpleanios();
        case XXQPPDFTCLIENTESHEADEREO:
            return getXxqpPdftClientesHeaderEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case HEADERID:
            setHeaderId((Number)value);
            return;
        case TIPOCONTACTO:
            setTipoContacto((String)value);
            return;
        case NOMBRE:
            setNombre((String)value);
            return;
        case DIRECCION:
            setDireccion((String)value);
            return;
        case TELEFONO:
            setTelefono((String)value);
            return;
        case CORREOELECTRONICO:
            setCorreoElectronico((String)value);
            return;
        case PUESTO:
            setPuesto((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case NUMEROCELULAR:
            setNumeroCelular((String)value);
            return;
        case CUMPLEANIOS:
            setCumpleanios((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity XxqpPdftClientesHeaderEOImpl
     */
    public XxqpPdftClientesHeaderEOImpl getXxqpPdftClientesHeaderEO() {
        return (XxqpPdftClientesHeaderEOImpl)getAttributeInternal(XXQPPDFTCLIENTESHEADEREO);
    }

    /**Sets <code>value</code> as the associated entity XxqpPdftClientesHeaderEOImpl
     */
    public void setXxqpPdftClientesHeaderEO(XxqpPdftClientesHeaderEOImpl value) {
        setAttributeInternal(XXQPPDFTCLIENTESHEADEREO, value);
    }

    /**Gets the attribute value for NumeroCelular, using the alias name NumeroCelular
     */
    public String getNumeroCelular() {
        return (String)getAttributeInternal(NUMEROCELULAR);
    }

    /**Sets <code>value</code> as the attribute value for NumeroCelular
     */
    public void setNumeroCelular(String value) {
        setAttributeInternal(NUMEROCELULAR, value);
    }

    /**Gets the attribute value for Cumpleanios, using the alias name Cumpleanios
     */
    public String getCumpleanios() {
        return (String)getAttributeInternal(CUMPLEANIOS);
    }

    /**Sets <code>value</code> as the attribute value for Cumpleanios
     */
    public void setCumpleanios(String value) {
        setAttributeInternal(CUMPLEANIOS, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number id) {
        return new Key(new Object[]{id});
    }
}
