DROP TABLE APPS.XXQP_PDFT_MYP_PROCESOS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXQP_PDFT_MYP_PROCESOS
(
  ID                    NUMBER,
  MYP_HEADER_ID         NUMBER,
  REGION                VARCHAR2(100 BYTE),
  PROSESO               VARCHAR2(30 BYTE),
  OTROS_PROCESOS        VARCHAR2(30 BYTE),
  SELECCIONAR           VARCHAR2(10 BYTE),
  PRECIO                NUMBER,
  COMENTARIOS_INSTRUCC  VARCHAR2(4000 BYTE),
  CREATED_BY            NUMBER(15)              NOT NULL,
  CREATION_DATE         DATE                    NOT NULL,
  LAST_UPDATED_BY       NUMBER(15)              NOT NULL,
  LAST_UPDATE_DATE      DATE                    NOT NULL,
  LAST_UPDATE_LOGIN     NUMBER(15),
  ATTRIBUTE_CATEGORY    VARCHAR2(250 BYTE),
  ATTRIBUTE1            VARCHAR2(2000 BYTE),
  ATTRIBUTE2            VARCHAR2(2000 BYTE),
  ATTRIBUTE3            VARCHAR2(2000 BYTE),
  ATTRIBUTE4            VARCHAR2(2000 BYTE),
  ATTRIBUTE5            VARCHAR2(2000 BYTE)
);


ALTER TABLE APPS.XXQP_PDFT_MYP_PROCESOS ADD (CONSTRAINT XXQP_PDFT_MYP_PROCESOS_FK FOREIGN KEY (MYP_HEADER_ID) REFERENCES APPS.XXQP_PDFT_MYP_HEADER (ID));
