DROP TABLE APPS.XXQP_PDFT_CLIENTES_CONTACTOS CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXQP_PDFT_CLIENTES_CONTACTOS
(
  ID                  NUMBER,
  HEADER_ID           NUMBER,
  TIPO_CONTACTO       VARCHAR2(200 BYTE),
  NOMBRE              VARCHAR2(150 BYTE),
  DIRECCION           VARCHAR2(300 BYTE),
  TELEFONO            VARCHAR2(100 BYTE),
  CORREO_ELECTRONICO  VARCHAR2(200 BYTE),
  PUESTO              VARCHAR2(150 BYTE),
  CREATED_BY          NUMBER(15)                NOT NULL,
  CREATION_DATE       DATE                      NOT NULL,
  LAST_UPDATED_BY     NUMBER(15)                NOT NULL,
  LAST_UPDATE_DATE    DATE                      NOT NULL,
  LAST_UPDATE_LOGIN   NUMBER(15),
  ATTRIBUTE_CATEGORY  VARCHAR2(250 BYTE),
  ATTRIBUTE1          VARCHAR2(2000 BYTE),
  ATTRIBUTE2          VARCHAR2(2000 BYTE),
  ATTRIBUTE3          VARCHAR2(2000 BYTE),
  ATTRIBUTE4          VARCHAR2(2000 BYTE),
  ATTRIBUTE5          VARCHAR2(2000 BYTE),
  NUMERO_CELULAR      VARCHAR2(100 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE APPS.XXQP_PDFT_CLIENTES_CONTACTOS ADD (
  CONSTRAINT XXQP_PDFT_CLIENTES_CONTA_FK 
  FOREIGN KEY (HEADER_ID) 
  REFERENCES APPS.XXQP_PDFT_CLIENTES_HEADER (ID));
