DROP TABLE APPS.XXQP_PDFT_MYP_COBERTURA CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXQP_PDFT_MYP_COBERTURA
(
  ID                   NUMBER,
  MYP_HEADER_ID        NUMBER,
  PLAZA_PROPIETARIA_C  VARCHAR2(30 BYTE),
  MENCIONAR_ESTADOS    VARCHAR2(300 BYTE),
  ENTREGA_LOCAL        NUMBER,
  DR_LOCAL             NUMBER,
  DI_LOCAL             NUMBER,
  ENTREGA_FORANEO      NUMBER,
  DR_FORANEO           NUMBER,
  DI_FORANEO           NUMBER,
  CREATED_BY           NUMBER(15)               NOT NULL,
  CREATION_DATE        DATE                     NOT NULL,
  LAST_UPDATED_BY      NUMBER(15)               NOT NULL,
  LAST_UPDATE_DATE     DATE                     NOT NULL,
  LAST_UPDATE_LOGIN    NUMBER(15),
  ATTRIBUTE_CATEGORY   VARCHAR2(250 BYTE),
  ATTRIBUTE1           VARCHAR2(2000 BYTE),
  ATTRIBUTE2           VARCHAR2(2000 BYTE),
  ATTRIBUTE3           VARCHAR2(2000 BYTE),
  ATTRIBUTE4           VARCHAR2(2000 BYTE),
  ATTRIBUTE5           VARCHAR2(2000 BYTE),
  TC_NACIONAL          VARCHAR2(250 BYTE),
  TC_REGIONAL          VARCHAR2(250 BYTE),
  TC_LOCAL             VARCHAR2(250 BYTE),
  COMENTARIOS          VARCHAR2(4000 BYTE)
);

ALTER TABLE APPS.XXQP_PDFT_MYP_COBERTURA ADD (CONSTRAINT XXQP_PDFT_MYP_COBERTURA_FK FOREIGN KEY (MYP_HEADER_ID)  REFERENCES APPS.XXQP_PDFT_MYP_HEADER (ID));

GRANT SELECT ON APPS.XXQP_PDFT_MYP_COBERTURA TO PREFACTURA;
