package xxqp.oracle.apps.ar.pdft.altafitec.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClientesInfoFiTecVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public ClientesInfoFiTecVOImpl() {
    }

    void filterClientesInfoFiTecVO(String pStrNombreDeCliente, 
                                   String pStrRFC) {
        if((null==pStrNombreDeCliente||"".equals(pStrNombreDeCliente))
        &&(null==pStrRFC||"".equals(pStrRFC))
          ){
         return;
        }
        /* 2. Create a view criteria row set for this view object  */
        ViewCriteria vc = this.createViewCriteria(); 
        /* 3. Use the view criteria to create one or more view criteria rows  */
        ViewCriteriaRow vcr1 = vc.createViewCriteriaRow(); 
        /* 4. Set attribute values to filter on in appropriate view criteria rows */ 
        if(null!=pStrNombreDeCliente&&!"".equals(pStrNombreDeCliente)){
        vcr1.setAttribute("KnownAs",pStrNombreDeCliente); 
        }
        if(null!=pStrRFC&&!"".equals(pStrRFC)){
        vcr1.setAttribute("JgzzFiscalCode",pStrRFC); 
        }
        
        /* 5. Add the view criteria rows to the view critera row set */
        vc.add(vcr1); 
        /* 6. Apply the view criteria to the view object */ 
        this.applyViewCriteria(vc); 
        /* 7. Execute the query */
        this.executeQuery();
        
    }

    void cleanClientesInfoFiTecVO() {
        /* 2. Create a view criteria row set for this view object  */
        ViewCriteria vc = this.createViewCriteria(); 
        /* 3. Use the view criteria to create one or more view criteria rows  */
        ViewCriteriaRow vcr1 = vc.createViewCriteriaRow(); 
        /* 4. Set attribute values to filter on in appropriate view criteria rows */ 
        vcr1.setAttribute("PartyId",new oracle.jbo.domain.Number(-1)); 
        /* 5. Add the view criteria rows to the view critera row set */
        vc.add(vcr1); 
        /* 6. Apply the view criteria to the view object */ 
        this.applyViewCriteria(vc); 
        /* 7. Execute the query */
        this.executeQuery();
    }
}
