package xxqp.oracle.apps.ar.pdft.altafitec.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FichasTecnicasVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public FichasTecnicasVOImpl() {
    }

    void initByFilters(Number pNumNoFichaTecnica
                      ,String pStrStatusValue
                      ,oracle.jbo.domain.Date  pFechaInicialOperacion
                      ,oracle.jbo.domain.Date  pFechaCreacion
                      ,String pStrEjecutivoCode
                      ,String pStrNombreDelClienteValue
                      ,String pStrUnidadDeNegocio
                      ,String pStrEmpresaQueFactura
                      ,String pStrCicloFacturacion
                      ) {
        if((null==pNumNoFichaTecnica||"".equals(pNumNoFichaTecnica))
          &&(null==pStrStatusValue||"".equals(pStrStatusValue))
          &&(null==pFechaInicialOperacion)
          &&(null==pFechaCreacion)
          &&(null==pStrEjecutivoCode)
          &&(null==pStrNombreDelClienteValue||"".equals(pStrNombreDelClienteValue))
          &&(null==pStrUnidadDeNegocio||"".equals(pStrUnidadDeNegocio))
          &&(null==pStrEmpresaQueFactura||"".equals(pStrEmpresaQueFactura))
          &&(null==pStrCicloFacturacion||"".equals(pStrCicloFacturacion))
          ){
         return; 
        }
        /* 2. Create a view criteria row set for this view object  */
        ViewCriteria vc = this.createViewCriteria(); 
        /* 3. Use the view criteria to create one or more view criteria rows  */
        ViewCriteriaRow vcr1 = vc.createViewCriteriaRow(); 
        /* 4. Set attribute values to filter on in appropriate view criteria rows */ 
        if(null!=pNumNoFichaTecnica&&!"".equals(pNumNoFichaTecnica)){
        vcr1.setAttribute("NumeroFt",pNumNoFichaTecnica); 
        }
        if(null!=pStrStatusValue&&!"".equals(pStrStatusValue)){
         vcr1.setAttribute("Status",pStrStatusValue); 
        }
        if(null!=pFechaInicialOperacion){
            vcr1.setAttribute("FechaInicialOperacion",pFechaInicialOperacion); 
        }
        if(null!=pFechaCreacion){
            vcr1.setAttribute("CreationDate",pFechaCreacion); 
        }
        if(null!=pStrEjecutivoCode){
            vcr1.setAttribute("EjecutivoCode",pStrEjecutivoCode); 
        } 
        if(null!=pStrNombreDelClienteValue&&!"".equals(pStrNombreDelClienteValue)){
            vcr1.setAttribute("NombreDelCliente",pStrNombreDelClienteValue+"%"); 
        } 
        if(null!=pStrUnidadDeNegocio&&!"".equals(pStrUnidadDeNegocio)){
            vcr1.setAttribute("UnidadDeNegocioC",pStrUnidadDeNegocio); 
        } 
        if(null!=pStrEmpresaQueFactura&&!"".equals(pStrEmpresaQueFactura)){
            vcr1.setAttribute("EmpresaQueFacturaC",pStrEmpresaQueFactura); 
        } 
        if(null!=pStrCicloFacturacion&&!"".equals(pStrCicloFacturacion)){
            vcr1.setAttribute("FrecuenciaFacturacionC",pStrCicloFacturacion); 
        } 
        /* 5. Add the view criteria rows to the view critera row set */
        vc.add(vcr1); 
        /* 6. Apply the view criteria to the view object */ 
        this.applyViewCriteria(vc); 
        /* 7. Execute the query */
        this.executeQuery();
    }
}
