package xxqp.oracle.apps.ar.pdft.altafitec.qplabs.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PreciosClientesTmpVORowImpl extends OAViewRowImpl {
    public static final int LINEID = 0;
    public static final int CONCEPTO = 1;
    public static final int PRECIO = 2;

    /**This is the default constructor (do not remove)
     */
    public PreciosClientesTmpVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute LineId
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**Gets the attribute value for the calculated attribute Concepto
     */
    public String getConcepto() {
        return (String) getAttributeInternal(CONCEPTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Concepto
     */
    public void setConcepto(String value) {
        setAttributeInternal(CONCEPTO, value);
    }

    /**Gets the attribute value for the calculated attribute Precio
     */
    public Number getPrecio() {
        return (Number) getAttributeInternal(PRECIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Precio
     */
    public void setPrecio(Number value) {
        setAttributeInternal(PRECIO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINEID:
            return getLineId();
        case CONCEPTO:
            return getConcepto();
        case PRECIO:
            return getPrecio();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINEID:
            setLineId((Number)value);
            return;
        case CONCEPTO:
            setConcepto((String)value);
            return;
        case PRECIO:
            setPrecio((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
