package xxqp.oracle.apps.ar.pdft.ss.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FichasTecnicasVORowImpl extends OAViewRowImpl {
    public static final int ID = 0;
    public static final int NUMEROFT = 1;
    public static final int STATUS = 2;
    public static final int PARTYID = 3;
    public static final int NOMBREDELCLIENTE = 4;
    public static final int UNIDADDENEGOCIOC = 5;
    public static final int EMPRESAQUEFACTURAC = 6;
    public static final int FRECUENCIAFACTURACIONC = 7;
    public static final int CREATEDBY = 8;
    public static final int EJECUTIVO = 9;
    public static final int FECHAINICIALOPERACION = 10;
    public static final int CREATIONDATE = 11;
    public static final int ORIGIN = 12;
    public static final int ISSELECTED = 13;

    /**This is the default constructor (do not remove)
     */
    public FichasTecnicasVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for the calculated attribute NumeroFt
     */
    public Number getNumeroFt() {
        return (Number) getAttributeInternal(NUMEROFT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NumeroFt
     */
    public void setNumeroFt(Number value) {
        setAttributeInternal(NUMEROFT, value);
    }

    /**Gets the attribute value for the calculated attribute Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for the calculated attribute PartyId
     */
    public Number getPartyId() {
        return (Number) getAttributeInternal(PARTYID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PartyId
     */
    public void setPartyId(Number value) {
        setAttributeInternal(PARTYID, value);
    }

    /**Gets the attribute value for the calculated attribute NombreDelCliente
     */
    public String getNombreDelCliente() {
        return (String) getAttributeInternal(NOMBREDELCLIENTE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute NombreDelCliente
     */
    public void setNombreDelCliente(String value) {
        setAttributeInternal(NOMBREDELCLIENTE, value);
    }

    /**Gets the attribute value for the calculated attribute UnidadDeNegocioC
     */
    public String getUnidadDeNegocioC() {
        return (String) getAttributeInternal(UNIDADDENEGOCIOC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute UnidadDeNegocioC
     */
    public void setUnidadDeNegocioC(String value) {
        setAttributeInternal(UNIDADDENEGOCIOC, value);
    }

    /**Gets the attribute value for the calculated attribute EmpresaQueFacturaC
     */
    public String getEmpresaQueFacturaC() {
        return (String) getAttributeInternal(EMPRESAQUEFACTURAC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmpresaQueFacturaC
     */
    public void setEmpresaQueFacturaC(String value) {
        setAttributeInternal(EMPRESAQUEFACTURAC, value);
    }

    /**Gets the attribute value for the calculated attribute FrecuenciaFacturacionC
     */
    public String getFrecuenciaFacturacionC() {
        return (String) getAttributeInternal(FRECUENCIAFACTURACIONC);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FrecuenciaFacturacionC
     */
    public void setFrecuenciaFacturacionC(String value) {
        setAttributeInternal(FRECUENCIAFACTURACIONC, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute Ejecutivo
     */
    public String getEjecutivo() {
        return (String) getAttributeInternal(EJECUTIVO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Ejecutivo
     */
    public void setEjecutivo(String value) {
        setAttributeInternal(EJECUTIVO, value);
    }

    /**Gets the attribute value for the calculated attribute FechaInicialOperacion
     */
    public Date getFechaInicialOperacion() {
        return (Date) getAttributeInternal(FECHAINICIALOPERACION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FechaInicialOperacion
     */
    public void setFechaInicialOperacion(Date value) {
        setAttributeInternal(FECHAINICIALOPERACION, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute Origin
     */
    public String getOrigin() {
        return (String) getAttributeInternal(ORIGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Origin
     */
    public void setOrigin(String value) {
        setAttributeInternal(ORIGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case NUMEROFT:
            return getNumeroFt();
        case STATUS:
            return getStatus();
        case PARTYID:
            return getPartyId();
        case NOMBREDELCLIENTE:
            return getNombreDelCliente();
        case UNIDADDENEGOCIOC:
            return getUnidadDeNegocioC();
        case EMPRESAQUEFACTURAC:
            return getEmpresaQueFacturaC();
        case FRECUENCIAFACTURACIONC:
            return getFrecuenciaFacturacionC();
        case CREATEDBY:
            return getCreatedBy();
        case EJECUTIVO:
            return getEjecutivo();
        case FECHAINICIALOPERACION:
            return getFechaInicialOperacion();
        case CREATIONDATE:
            return getCreationDate();
        case ORIGIN:
            return getOrigin();
        case ISSELECTED:
            return getIsSelected();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ISSELECTED:
            setIsSelected((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute IsSelected
     */
    public String getIsSelected() {
        return (String) getAttributeInternal(ISSELECTED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsSelected
     */
    public void setIsSelected(String value) {
        setAttributeInternal(ISSELECTED, value);
    }
}
