package xxqp.oracle.apps.ar.pdft.ss.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxqpPdftUsuariosRoVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public XxqpPdftUsuariosRoVOImpl() {
    }

    void initByUserPassword(String strUsuario, String strConstrasenia) {
        // 2. Create a view criteria row set for this view object
        ViewCriteria vc = this.createViewCriteria(); 
        // 3. Use the view criteria to create one or more view criteria rows
        ViewCriteriaRow vcr1 = vc.createViewCriteriaRow(); 
        // 4. Set attribute values to filter on in appropriate view criteria rows
        vcr1.setAttribute("Usuario",strUsuario); 
        vcr1.setAttribute("Password",strConstrasenia); 
        vcr1.setAttribute("Status","Y");
        // 5. Add the view criteria rows to the view critera row set 
        vc.add(vcr1); 
        // 6. Apply the view criteria to the view object
        this.applyViewCriteria(vc); 
        // 7. Execute the query
        this.executeQuery();
    }
}
