package xxqp.oracle.apps.ar.pdft.altafitec.bpo.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BpoHeaderTmpVORowImpl extends OAViewRowImpl {
    public static final int CONTRATOFILE = 0;
    public static final int CONTRATOFILENAME = 1;
    public static final int CONTRATO = 2;
    public static final int FECHAINICIOOPERACION = 3;
    public static final int FILE1 = 4;
    public static final int FILENAME1 = 5;
    public static final int FILE2 = 6;
    public static final int FILENAME2 = 7;
    public static final int FILE3 = 8;
    public static final int FILENAME3 = 9;
    public static final int CURRENCYCODE = 10;

    /**This is the default constructor (do not remove)
     */
    public BpoHeaderTmpVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute ContratoFile
     */
    public BlobDomain getContratoFile() {
        return (BlobDomain) getAttributeInternal(CONTRATOFILE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ContratoFile
     */
    public void setContratoFile(BlobDomain value) {
        if(null!=value){
          this.setContrato("Y");
        }else{
          this.setContrato("N");
        }
        setAttributeInternal(CONTRATOFILE, value);
    }

    /**Gets the attribute value for the calculated attribute ContratoFileName
     */
    public String getContratoFileName() {
        return (String) getAttributeInternal(CONTRATOFILENAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ContratoFileName
     */
    public void setContratoFileName(String value) {
        setAttributeInternal(CONTRATOFILENAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CONTRATOFILE:
            return getContratoFile();
        case CONTRATOFILENAME:
            return getContratoFileName();
        case CONTRATO:
            return getContrato();
        case FECHAINICIOOPERACION:
            return getFechaInicioOperacion();
        case FILE1:
            return getFile1();
        case FILENAME1:
            return getFileName1();
        case FILE2:
            return getFile2();
        case FILENAME2:
            return getFileName2();
        case FILE3:
            return getFile3();
        case FILENAME3:
            return getFileName3();
        case CURRENCYCODE:
            return getCurrencyCode();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CONTRATOFILE:
            setContratoFile((BlobDomain)value);
            return;
        case CONTRATOFILENAME:
            setContratoFileName((String)value);
            return;
        case CONTRATO:
            setContrato((String)value);
            return;
        case FECHAINICIOOPERACION:
            setFechaInicioOperacion((Date)value);
            return;
        case FILE1:
            setFile1((BlobDomain)value);
            return;
        case FILENAME1:
            setFileName1((String)value);
            return;
        case FILE2:
            setFile2((BlobDomain)value);
            return;
        case FILENAME2:
            setFileName2((String)value);
            return;
        case FILE3:
            setFile3((BlobDomain)value);
            return;
        case FILENAME3:
            setFileName3((String)value);
            return;
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Contrato
     */
    public String getContrato() {
        return (String) getAttributeInternal(CONTRATO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Contrato
     */
    public void setContrato(String value) {
        setAttributeInternal(CONTRATO, value);
    }

    /**Gets the attribute value for the calculated attribute FechaInicioOperacion
     */
    public Date getFechaInicioOperacion() {
        return (Date) getAttributeInternal(FECHAINICIOOPERACION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FechaInicioOperacion
     */
    public void setFechaInicioOperacion(Date value) {
        setAttributeInternal(FECHAINICIOOPERACION, value);
    }

    /**Gets the attribute value for the calculated attribute File1
     */
    public BlobDomain getFile1() {
        return (BlobDomain) getAttributeInternal(FILE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute File1
     */
    public void setFile1(BlobDomain value) {
        setAttributeInternal(FILE1, value);
    }

    /**Gets the attribute value for the calculated attribute FileName1
     */
    public String getFileName1() {
        return (String) getAttributeInternal(FILENAME1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FileName1
     */
    public void setFileName1(String value) {
        setAttributeInternal(FILENAME1, value);
    }

    /**Gets the attribute value for the calculated attribute File2
     */
    public BlobDomain getFile2() {
        return (BlobDomain) getAttributeInternal(FILE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute File2
     */
    public void setFile2(BlobDomain value) {
        setAttributeInternal(FILE2, value);
    }

    /**Gets the attribute value for the calculated attribute FileName2
     */
    public String getFileName2() {
        return (String) getAttributeInternal(FILENAME2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FileName2
     */
    public void setFileName2(String value) {
        setAttributeInternal(FILENAME2, value);
    }

    /**Gets the attribute value for the calculated attribute File3
     */
    public BlobDomain getFile3() {
        return (BlobDomain) getAttributeInternal(FILE3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute File3
     */
    public void setFile3(BlobDomain value) {
        setAttributeInternal(FILE3, value);
    }

    /**Gets the attribute value for the calculated attribute FileName3
     */
    public String getFileName3() {
        return (String) getAttributeInternal(FILENAME3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FileName3
     */
    public void setFileName3(String value) {
        setAttributeInternal(FILENAME3, value);
    }

    /**Gets the attribute value for the calculated attribute CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }
}
