package xxqp.oracle.apps.ar.pdft.altafitec.bpo.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PrecioTmpVORowImpl extends OAViewRowImpl {
    public static final int LINE = 0;
    public static final int CONCEPTO = 1;
    public static final int CANTIDAD = 2;
    public static final int PRECIOUNITARIO = 3;
    public static final int TOTALPORCONCEPTO = 4;
    public static final int SELECTEDFLAG = 5;

    /**This is the default constructor (do not remove)
     */
    public PrecioTmpVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Line
     */
    public Number getLine() {
        return (Number) getAttributeInternal(LINE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Line
     */
    public void setLine(Number value) {
        setAttributeInternal(LINE, value);
    }

    /**Gets the attribute value for the calculated attribute Concepto
     */
    public String getConcepto() {
        return (String) getAttributeInternal(CONCEPTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Concepto
     */
    public void setConcepto(String value) {
        setAttributeInternal(CONCEPTO, value);
    }

    /**Gets the attribute value for the calculated attribute Cantidad
     */
    public Number getCantidad() {
        return (Number) getAttributeInternal(CANTIDAD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cantidad
     */
    public void setCantidad(Number value) {
        setAttributeInternal(CANTIDAD, value);
    }

    /**Gets the attribute value for the calculated attribute PrecioUnitario
     */
    public Number getPrecioUnitario() {
        return (Number) getAttributeInternal(PRECIOUNITARIO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PrecioUnitario
     */
    public void setPrecioUnitario(Number value) {
        setAttributeInternal(PRECIOUNITARIO, value);
    }

    /**Gets the attribute value for the calculated attribute TotalPorConcepto
     */
    public Number getTotalPorConcepto() {
        return (Number) getAttributeInternal(TOTALPORCONCEPTO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TotalPorConcepto
     */
    public void setTotalPorConcepto(Number value) {
        setAttributeInternal(TOTALPORCONCEPTO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINE:
            return getLine();
        case CONCEPTO:
            return getConcepto();
        case CANTIDAD:
            return getCantidad();
        case PRECIOUNITARIO:
            return getPrecioUnitario();
        case TOTALPORCONCEPTO:
            return getTotalPorConcepto();
        case SELECTEDFLAG:
            return getSelectedFlag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case LINE:
            setLine((Number)value);
            return;
        case CONCEPTO:
            setConcepto((String)value);
            return;
        case CANTIDAD:
            setCantidad((Number)value);
            return;
        case PRECIOUNITARIO:
            setPrecioUnitario((Number)value);
            return;
        case TOTALPORCONCEPTO:
            setTotalPorConcepto((Number)value);
            return;
        case SELECTEDFLAG:
            setSelectedFlag((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute SelectedFlag
     */
    public String getSelectedFlag() {
        return (String) getAttributeInternal(SELECTEDFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SelectedFlag
     */
    public void setSelectedFlag(String value) {
        setAttributeInternal(SELECTEDFLAG, value);
    }
}
