package xxqp.oracle.apps.ar.pdft.altafitec.bpo.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import xxqp.oracle.apps.ar.pdft.altafitec.bpo.schema.server.XxqpPdftBpoRegNegEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxqpPdftBpoRegNegVORowImpl extends OAViewRowImpl {
    public static final int ID = 0;
    public static final int BPOHEADERID = 1;
    public static final int ESTADOCODE = 2;
    public static final int CONCEPTOCODE = 3;
    public static final int PRECIO = 4;
    public static final int CREATEDBY = 5;
    public static final int CREATIONDATE = 6;
    public static final int LASTUPDATEDBY = 7;
    public static final int LASTUPDATEDATE = 8;
    public static final int LASTUPDATELOGIN = 9;
    public static final int ATTRIBUTECATEGORY = 10;
    public static final int ATTRIBUTE1 = 11;
    public static final int ATTRIBUTE2 = 12;
    public static final int ATTRIBUTE3 = 13;
    public static final int ATTRIBUTE4 = 14;
    public static final int ATTRIBUTE5 = 15;
    public static final int ESTADOMEANING = 16;
    public static final int CONCEPTOMEANING = 17;

    /**This is the default constructor (do not remove)
     */
    public XxqpPdftBpoRegNegVORowImpl() {
    }

    /**Gets XxqpPdftBpoRegNegEO entity object.
     */
    public XxqpPdftBpoRegNegEOImpl getXxqpPdftBpoRegNegEO() {
        return (XxqpPdftBpoRegNegEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ID using the alias name Id
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as attribute value for ID using the alias name Id
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for BPO_HEADER_ID using the alias name BpoHeaderId
     */
    public Number getBpoHeaderId() {
        return (Number) getAttributeInternal(BPOHEADERID);
    }

    /**Sets <code>value</code> as attribute value for BPO_HEADER_ID using the alias name BpoHeaderId
     */
    public void setBpoHeaderId(Number value) {
        setAttributeInternal(BPOHEADERID, value);
    }

    /**Gets the attribute value for ESTADO_CODE using the alias name EstadoCode
     */
    public String getEstadoCode() {
        return (String) getAttributeInternal(ESTADOCODE);
    }

    /**Sets <code>value</code> as attribute value for ESTADO_CODE using the alias name EstadoCode
     */
    public void setEstadoCode(String value) {
        setAttributeInternal(ESTADOCODE, value);
    }

    /**Gets the attribute value for CONCEPTO_CODE using the alias name ConceptoCode
     */
    public String getConceptoCode() {
        return (String) getAttributeInternal(CONCEPTOCODE);
    }

    /**Sets <code>value</code> as attribute value for CONCEPTO_CODE using the alias name ConceptoCode
     */
    public void setConceptoCode(String value) {
        setAttributeInternal(CONCEPTOCODE, value);
    }

    /**Gets the attribute value for PRECIO using the alias name Precio
     */
    public Number getPrecio() {
        return (Number) getAttributeInternal(PRECIO);
    }

    /**Sets <code>value</code> as attribute value for PRECIO using the alias name Precio
     */
    public void setPrecio(Number value) {
        setAttributeInternal(PRECIO, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case BPOHEADERID:
            return getBpoHeaderId();
        case ESTADOCODE:
            return getEstadoCode();
        case CONCEPTOCODE:
            return getConceptoCode();
        case PRECIO:
            return getPrecio();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ESTADOMEANING:
            return getEstadoMeaning();
        case CONCEPTOMEANING:
            return getConceptoMeaning();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            setId((Number)value);
            return;
        case BPOHEADERID:
            setBpoHeaderId((Number)value);
            return;
        case ESTADOCODE:
            setEstadoCode((String)value);
            return;
        case CONCEPTOCODE:
            setConceptoCode((String)value);
            return;
        case PRECIO:
            setPrecio((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ESTADOMEANING:
            setEstadoMeaning((String)value);
            return;
        case CONCEPTOMEANING:
            setConceptoMeaning((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute EstadoMeaning
     */
    public String getEstadoMeaning() {
        return (String) getAttributeInternal(ESTADOMEANING);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EstadoMeaning
     */
    public void setEstadoMeaning(String value) {
        setAttributeInternal(ESTADOMEANING, value);
    }

    /**Gets the attribute value for the calculated attribute ConceptoMeaning
     */
    public String getConceptoMeaning() {
        return (String) getAttributeInternal(CONCEPTOMEANING);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ConceptoMeaning
     */
    public void setConceptoMeaning(String value) {
        setAttributeInternal(CONCEPTOMEANING, value);
    }
}
